// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_9_7_5_3_0_ap_ufixed_8_6_5_3_0_ReLU_config6_s (
        ap_ready,
        data_6_val,
        data_12_val,
        data_41_val,
        data_54_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_rst
);


output   ap_ready;
input  [8:0] data_6_val;
input  [8:0] data_12_val;
input  [8:0] data_41_val;
input  [8:0] data_54_val;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
input   ap_rst;

wire   [0:0] icmp_ln45_fu_48_p2;
wire   [7:0] trunc_ln46_fu_54_p1;
wire   [0:0] icmp_ln45_1_fu_66_p2;
wire   [7:0] trunc_ln46_1_fu_72_p1;
wire   [0:0] icmp_ln45_2_fu_84_p2;
wire   [7:0] trunc_ln46_2_fu_90_p1;
wire   [0:0] icmp_ln45_3_fu_102_p2;
wire   [7:0] trunc_ln46_3_fu_108_p1;
wire   [7:0] select_ln45_fu_58_p3;
wire   [7:0] select_ln45_1_fu_76_p3;
wire   [7:0] select_ln45_2_fu_94_p3;
wire   [7:0] select_ln45_3_fu_112_p3;

assign ap_ready = 1'b1;

assign select_ln45_1_fu_76_p3 = ((icmp_ln45_1_fu_66_p2[0:0] == 1'b1) ? trunc_ln46_1_fu_72_p1 : 8'd0);

assign select_ln45_2_fu_94_p3 = ((icmp_ln45_2_fu_84_p2[0:0] == 1'b1) ? trunc_ln46_2_fu_90_p1 : 8'd0);

assign select_ln45_3_fu_112_p3 = ((icmp_ln45_3_fu_102_p2[0:0] == 1'b1) ? trunc_ln46_3_fu_108_p1 : 8'd0);

assign select_ln45_fu_58_p3 = ((icmp_ln45_fu_48_p2[0:0] == 1'b1) ? trunc_ln46_fu_54_p1 : 8'd0);

assign trunc_ln46_1_fu_72_p1 = data_12_val[7:0];

assign trunc_ln46_2_fu_90_p1 = data_41_val[7:0];

assign trunc_ln46_3_fu_108_p1 = data_54_val[7:0];

assign trunc_ln46_fu_54_p1 = data_6_val[7:0];

assign ap_return_0 = select_ln45_fu_58_p3;

assign ap_return_1 = select_ln45_1_fu_76_p3;

assign ap_return_2 = select_ln45_2_fu_94_p3;

assign ap_return_3 = select_ln45_3_fu_112_p3;

assign icmp_ln45_1_fu_66_p2 = (($signed(data_12_val) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_84_p2 = (($signed(data_41_val) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_102_p2 = (($signed(data_54_val) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_48_p2 = (($signed(data_6_val) > $signed(9'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_9_7_5_3_0_ap_ufixed_8_6_5_3_0_ReLU_config6_s
