-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_11_6_5_3_0_ap_fixed_9_7_5_3_0_config3_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (9 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (8 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (7 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (9 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (8 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_dense_latency_ap_fixed_11_6_5_3_0_ap_fixed_9_7_5_3_0_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv21_8000 : STD_LOGIC_VECTOR (20 downto 0) := "000001000000000000000";
    constant ap_const_lv23_24000 : STD_LOGIC_VECTOR (22 downto 0) := "00000100100000000000000";
    constant ap_const_lv23_7D8000 : STD_LOGIC_VECTOR (22 downto 0) := "11111011000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv22_6000 : STD_LOGIC_VECTOR (21 downto 0) := "0000000110000000000000";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal sext_ln33_1_fu_170_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln33_2_fu_174_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln33_4_fu_182_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mult_fu_186_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mult_fu_186_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal tmp_26_fu_198_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_26_fu_198_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal mult_4_fu_210_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln73_fu_218_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mult_5_fu_222_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mult_5_fu_222_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln42_fu_234_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mult_6_fu_238_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mult_6_fu_238_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal mult_7_fu_250_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mult_7_fu_250_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln73_1_fu_262_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal mult_8_fu_266_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mult_8_fu_266_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal mult_9_fu_278_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sext_ln17_fu_194_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mult_4_fu_210_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_3_fu_274_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln58_fu_292_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal sext_ln58_fu_298_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_2_fu_230_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln58_1_fu_302_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln58_fu_286_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln73_fu_218_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln73_1_fu_262_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp36_fu_314_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp36_cast_fu_320_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln42_fu_234_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp5_fu_324_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_330_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln33_3_fu_178_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln33_4_fu_182_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp772_fu_342_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_348_p3 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp8_fu_356_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln17_2_fu_258_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_12_fu_360_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln42_1_fu_206_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal mult_9_fu_278_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_13_fu_372_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_shl_fu_338_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln58_3_fu_378_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln58_2_fu_366_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal data_12_val_cast10_fu_390_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_11_val_cast11_fu_394_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal data_15_val_cast22_fu_398_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal data_12_val_cast10_fu_390_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal data_11_val_cast11_fu_394_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_fu_402_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal data_15_val_cast22_fu_398_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_cast_fu_408_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp1170_fu_412_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sext_ln33_2_fu_174_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln33_fu_166_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp41_fu_426_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sext_ln33_1_fu_170_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp1468_fu_432_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp15_fu_438_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp12_fu_418_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_16_fu_452_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_15_fu_446_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal data_8_val_cast13_fu_464_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp1666_fu_468_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_17_fu_474_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal data_7_val_cast15_fu_486_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal data_7_val_cast15_fu_486_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp1964_fu_490_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_18_fu_496_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal sext_ln17_1_fu_246_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_18_fu_508_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln58_4_fu_504_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal sub_ln58_4_fu_520_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_20_cast_fu_482_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal add_ln58_20_fu_530_p2 : STD_LOGIC_VECTOR (21 downto 0);
    signal sext_ln58_6_fu_536_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal sext_ln58_5_fu_526_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_21_fu_540_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_19_fu_514_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_14_fu_384_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_17_fu_458_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_22_fu_546_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln58_11_fu_308_p2 : STD_LOGIC_VECTOR (22 downto 0);


begin



    add_ln58_11_fu_308_p2 <= std_logic_vector(unsigned(sub_ln58_1_fu_302_p2) + unsigned(sub_ln58_fu_286_p2));
    add_ln58_12_fu_360_p2 <= std_logic_vector(signed(tmp8_fu_356_p1) + signed(sext_ln17_2_fu_258_p1));
    add_ln58_13_fu_372_p2 <= std_logic_vector(unsigned(mult_9_fu_278_p3) + unsigned(ap_const_lv23_24000));
    add_ln58_14_fu_384_p2 <= std_logic_vector(unsigned(sub_ln58_3_fu_378_p2) + unsigned(sub_ln58_2_fu_366_p2));
    add_ln58_15_fu_446_p2 <= std_logic_vector(unsigned(tmp15_fu_438_p3) + unsigned(sext_ln17_2_fu_258_p1));
    add_ln58_16_fu_452_p2 <= std_logic_vector(unsigned(tmp12_fu_418_p3) + unsigned(ap_const_lv23_7D8000));
    add_ln58_17_fu_458_p2 <= std_logic_vector(unsigned(add_ln58_16_fu_452_p2) + unsigned(add_ln58_15_fu_446_p2));
    add_ln58_18_fu_508_p2 <= std_logic_vector(signed(sext_ln42_2_fu_230_p1) + signed(sext_ln17_1_fu_246_p1));
    add_ln58_19_fu_514_p2 <= std_logic_vector(unsigned(add_ln58_18_fu_508_p2) + unsigned(mult_4_fu_210_p3));
    add_ln58_20_fu_530_p2 <= std_logic_vector(signed(tmp_20_cast_fu_482_p1) + signed(ap_const_lv22_6000));
    add_ln58_21_fu_540_p2 <= std_logic_vector(signed(sext_ln58_6_fu_536_p1) + signed(sext_ln58_5_fu_526_p1));
    add_ln58_22_fu_546_p2 <= std_logic_vector(unsigned(add_ln58_21_fu_540_p2) + unsigned(add_ln58_19_fu_514_p2));
    add_ln58_fu_292_p2 <= std_logic_vector(signed(sext_ln42_3_fu_274_p1) + signed(ap_const_lv21_8000));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln58_14_fu_384_p2(22 downto 14);
    ap_return_1 <= add_ln58_17_fu_458_p2(22 downto 14);
    ap_return_2 <= add_ln58_22_fu_546_p2(22 downto 14);
    ap_return_3 <= add_ln58_11_fu_308_p2(22 downto 14);
    data_11_val_cast11_fu_394_p0 <= data_11_val;
        data_11_val_cast11_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_11_val_cast11_fu_394_p0),9));

    data_12_val_cast10_fu_390_p0 <= data_12_val;
        data_12_val_cast10_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_12_val_cast10_fu_390_p0),9));

    data_15_val_cast22_fu_398_p0 <= data_15_val;
        data_15_val_cast22_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_15_val_cast22_fu_398_p0),10));

    data_7_val_cast15_fu_486_p0 <= data_7_val;
        data_7_val_cast15_fu_486_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_7_val_cast15_fu_486_p0),10));

        data_8_val_cast13_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_8_val),10));

    empty_fu_402_p2 <= std_logic_vector(signed(data_12_val_cast10_fu_390_p1) + signed(data_11_val_cast11_fu_394_p1));
    mult_4_fu_210_p1 <= data_2_val;
    mult_4_fu_210_p3 <= (mult_4_fu_210_p1 & ap_const_lv14_0);
    mult_5_fu_222_p1 <= data_4_val;
    mult_5_fu_222_p3 <= (mult_5_fu_222_p1 & ap_const_lv13_0);
    mult_6_fu_238_p1 <= data_6_val;
    mult_6_fu_238_p3 <= (mult_6_fu_238_p1 & ap_const_lv9_0);
    mult_7_fu_250_p1 <= data_7_val;
    mult_7_fu_250_p3 <= (mult_7_fu_250_p1 & ap_const_lv11_0);
    mult_8_fu_266_p1 <= data_12_val;
    mult_8_fu_266_p3 <= (mult_8_fu_266_p1 & ap_const_lv12_0);
    mult_9_fu_278_p1 <= data_15_val;
    mult_9_fu_278_p3 <= (mult_9_fu_278_p1 & ap_const_lv14_0);
    mult_fu_186_p1 <= data_0_val;
    mult_fu_186_p3 <= (mult_fu_186_p1 & ap_const_lv11_0);
        p_cast_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(empty_fu_402_p2),10));

        p_shl_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_330_p3),23));

        sext_ln17_1_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mult_6_fu_238_p3),23));

        sext_ln17_2_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mult_7_fu_250_p3),23));

        sext_ln17_fu_194_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mult_fu_186_p3),23));

    sext_ln33_1_fu_170_p0 <= data_4_val;
        sext_ln33_1_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln33_1_fu_170_p0),11));

    sext_ln33_2_fu_174_p0 <= data_2_val;
        sext_ln33_2_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln33_2_fu_174_p0),11));

        sext_ln33_3_fu_178_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val),10));

    sext_ln33_4_fu_182_p0 <= data_0_val;
        sext_ln33_4_fu_182_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln33_4_fu_182_p0),10));

        sext_ln33_fu_166_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_5_val),11));

        sext_ln42_1_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_26_fu_198_p3),23));

        sext_ln42_2_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mult_5_fu_222_p3),23));

        sext_ln42_3_fu_274_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mult_8_fu_266_p3),21));

    sext_ln42_fu_234_p0 <= data_6_val;
        sext_ln42_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln42_fu_234_p0),11));

        sext_ln58_4_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_18_fu_496_p3),21));

        sext_ln58_5_fu_526_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln58_4_fu_520_p2),23));

        sext_ln58_6_fu_536_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_20_fu_530_p2),23));

        sext_ln58_fu_298_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln58_fu_292_p2),23));

    sext_ln73_1_fu_262_p0 <= data_11_val;
        sext_ln73_1_fu_262_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln73_1_fu_262_p0),10));

    sext_ln73_fu_218_p0 <= data_4_val;
        sext_ln73_fu_218_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln73_fu_218_p0),10));

    sub_ln58_1_fu_302_p2 <= std_logic_vector(signed(sext_ln58_fu_298_p1) - signed(sext_ln42_2_fu_230_p1));
    sub_ln58_2_fu_366_p2 <= std_logic_vector(unsigned(add_ln58_12_fu_360_p2) - unsigned(sext_ln42_1_fu_206_p1));
    sub_ln58_3_fu_378_p2 <= std_logic_vector(unsigned(add_ln58_13_fu_372_p2) - unsigned(p_shl_fu_338_p1));
    sub_ln58_4_fu_520_p2 <= std_logic_vector(signed(sext_ln58_4_fu_504_p1) - signed(sext_ln42_3_fu_274_p1));
    sub_ln58_fu_286_p2 <= std_logic_vector(signed(sext_ln17_fu_194_p1) - signed(mult_4_fu_210_p3));
    tmp1170_fu_412_p2 <= std_logic_vector(signed(data_15_val_cast22_fu_398_p1) - signed(p_cast_fu_408_p1));
    tmp12_fu_418_p3 <= (tmp1170_fu_412_p2 & ap_const_lv13_0);
    tmp1468_fu_432_p2 <= std_logic_vector(unsigned(tmp41_fu_426_p2) + unsigned(sext_ln33_1_fu_170_p1));
    tmp15_fu_438_p3 <= (tmp1468_fu_432_p2 & ap_const_lv12_0);
    tmp1666_fu_468_p2 <= std_logic_vector(signed(data_15_val_cast22_fu_398_p1) + signed(data_8_val_cast13_fu_464_p1));
    tmp1964_fu_490_p2 <= std_logic_vector(signed(sext_ln33_4_fu_182_p1) - signed(data_7_val_cast15_fu_486_p1));
        tmp36_cast_fu_320_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp36_fu_314_p2),11));

    tmp36_fu_314_p2 <= std_logic_vector(signed(sext_ln73_fu_218_p1) + signed(sext_ln73_1_fu_262_p1));
    tmp41_fu_426_p2 <= std_logic_vector(signed(sext_ln33_2_fu_174_p1) + signed(sext_ln33_fu_166_p1));
    tmp5_fu_324_p2 <= std_logic_vector(signed(tmp36_cast_fu_320_p1) + signed(sext_ln42_fu_234_p1));
    tmp772_fu_342_p2 <= std_logic_vector(signed(sext_ln33_3_fu_178_p1) + signed(sext_ln33_4_fu_182_p1));
        tmp8_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_348_p3),23));

    tmp_17_fu_474_p3 <= (tmp1666_fu_468_p2 & ap_const_lv11_0);
    tmp_18_fu_496_p3 <= (tmp1964_fu_490_p2 & ap_const_lv10_0);
        tmp_20_cast_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_17_fu_474_p3),22));

    tmp_26_fu_198_p1 <= data_2_val;
    tmp_26_fu_198_p3 <= (tmp_26_fu_198_p1 & ap_const_lv13_0);
    tmp_fu_330_p3 <= (tmp5_fu_324_p2 & ap_const_lv11_0);
    tmp_s_fu_348_p3 <= (tmp772_fu_342_p2 & ap_const_lv12_0);
end behav;
