-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_11_8_5_3_0_ap_ufixed_10_7_5_3_0_ReLU_config6_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_49_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_55_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_59_val : IN STD_LOGIC_VECTOR (10 downto 0);
    data_63_val : IN STD_LOGIC_VECTOR (10 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_relu_ap_fixed_11_8_5_3_0_ap_ufixed_10_7_5_3_0_ReLU_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_88_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_fu_94_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_11_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_11_fu_112_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_12_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_12_fu_130_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_13_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_13_fu_148_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_14_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_14_fu_166_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_15_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_15_fu_184_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_16_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_16_fu_202_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_17_fu_214_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_17_fu_220_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln45_18_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_18_fu_238_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_fu_98_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_11_fu_116_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_12_fu_134_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_13_fu_152_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_14_fu_170_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_15_fu_188_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_16_fu_206_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_17_fu_224_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln45_18_fu_242_p3 : STD_LOGIC_VECTOR (9 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln45_fu_98_p3;
    ap_return_1 <= select_ln45_11_fu_116_p3;
    ap_return_2 <= select_ln45_12_fu_134_p3;
    ap_return_3 <= select_ln45_13_fu_152_p3;
    ap_return_4 <= select_ln45_14_fu_170_p3;
    ap_return_5 <= select_ln45_15_fu_188_p3;
    ap_return_6 <= select_ln45_16_fu_206_p3;
    ap_return_7 <= select_ln45_17_fu_224_p3;
    ap_return_8 <= select_ln45_18_fu_242_p3;
    icmp_ln45_11_fu_106_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_12_fu_124_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_13_fu_142_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_14_fu_160_p2 <= "1" when (signed(data_22_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_15_fu_178_p2 <= "1" when (signed(data_49_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_16_fu_196_p2 <= "1" when (signed(data_55_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_17_fu_214_p2 <= "1" when (signed(data_59_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_18_fu_232_p2 <= "1" when (signed(data_63_val) > signed(ap_const_lv11_0)) else "0";
    icmp_ln45_fu_88_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv11_0)) else "0";
    select_ln45_11_fu_116_p3 <= 
        trunc_ln46_11_fu_112_p1 when (icmp_ln45_11_fu_106_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_12_fu_134_p3 <= 
        trunc_ln46_12_fu_130_p1 when (icmp_ln45_12_fu_124_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_13_fu_152_p3 <= 
        trunc_ln46_13_fu_148_p1 when (icmp_ln45_13_fu_142_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_14_fu_170_p3 <= 
        trunc_ln46_14_fu_166_p1 when (icmp_ln45_14_fu_160_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_15_fu_188_p3 <= 
        trunc_ln46_15_fu_184_p1 when (icmp_ln45_15_fu_178_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_16_fu_206_p3 <= 
        trunc_ln46_16_fu_202_p1 when (icmp_ln45_16_fu_196_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_17_fu_224_p3 <= 
        trunc_ln46_17_fu_220_p1 when (icmp_ln45_17_fu_214_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_18_fu_242_p3 <= 
        trunc_ln46_18_fu_238_p1 when (icmp_ln45_18_fu_232_p2(0) = '1') else 
        ap_const_lv10_0;
    select_ln45_fu_98_p3 <= 
        trunc_ln46_fu_94_p1 when (icmp_ln45_fu_88_p2(0) = '1') else 
        ap_const_lv10_0;
    trunc_ln46_11_fu_112_p1 <= data_1_val(10 - 1 downto 0);
    trunc_ln46_12_fu_130_p1 <= data_6_val(10 - 1 downto 0);
    trunc_ln46_13_fu_148_p1 <= data_7_val(10 - 1 downto 0);
    trunc_ln46_14_fu_166_p1 <= data_22_val(10 - 1 downto 0);
    trunc_ln46_15_fu_184_p1 <= data_49_val(10 - 1 downto 0);
    trunc_ln46_16_fu_202_p1 <= data_55_val(10 - 1 downto 0);
    trunc_ln46_17_fu_220_p1 <= data_59_val(10 - 1 downto 0);
    trunc_ln46_18_fu_238_p1 <= data_63_val(10 - 1 downto 0);
    trunc_ln46_fu_94_p1 <= data_0_val(10 - 1 downto 0);
end behav;
