// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_13_8_5_3_0_ap_ufixed_12_7_5_3_0_ReLU_config6_s (
        ap_ready,
        data_2_val,
        data_3_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_10_val,
        data_14_val,
        data_17_val,
        data_19_val,
        data_20_val,
        data_25_val,
        data_33_val,
        data_36_val,
        data_37_val,
        data_38_val,
        data_46_val,
        data_50_val,
        data_57_val,
        data_61_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_rst
);


output   ap_ready;
input  [12:0] data_2_val;
input  [12:0] data_3_val;
input  [12:0] data_5_val;
input  [12:0] data_6_val;
input  [12:0] data_7_val;
input  [12:0] data_10_val;
input  [12:0] data_14_val;
input  [12:0] data_17_val;
input  [12:0] data_19_val;
input  [12:0] data_20_val;
input  [12:0] data_25_val;
input  [12:0] data_33_val;
input  [12:0] data_36_val;
input  [12:0] data_37_val;
input  [12:0] data_38_val;
input  [12:0] data_46_val;
input  [12:0] data_50_val;
input  [12:0] data_57_val;
input  [12:0] data_61_val;
output  [11:0] ap_return_0;
output  [11:0] ap_return_1;
output  [11:0] ap_return_2;
output  [11:0] ap_return_3;
output  [11:0] ap_return_4;
output  [11:0] ap_return_5;
output  [11:0] ap_return_6;
output  [11:0] ap_return_7;
output  [11:0] ap_return_8;
output  [11:0] ap_return_9;
output  [11:0] ap_return_10;
output  [11:0] ap_return_11;
output  [11:0] ap_return_12;
output  [11:0] ap_return_13;
output  [11:0] ap_return_14;
output  [11:0] ap_return_15;
output  [11:0] ap_return_16;
output  [11:0] ap_return_17;
output  [11:0] ap_return_18;
input   ap_rst;

wire   [0:0] icmp_ln45_fu_168_p2;
wire   [11:0] trunc_ln46_fu_174_p1;
wire   [0:0] icmp_ln45_1_fu_186_p2;
wire   [11:0] trunc_ln46_1_fu_192_p1;
wire   [0:0] icmp_ln45_2_fu_204_p2;
wire   [11:0] trunc_ln46_2_fu_210_p1;
wire   [0:0] icmp_ln45_3_fu_222_p2;
wire   [11:0] trunc_ln46_3_fu_228_p1;
wire   [0:0] icmp_ln45_4_fu_240_p2;
wire   [11:0] trunc_ln46_4_fu_246_p1;
wire   [0:0] icmp_ln45_5_fu_258_p2;
wire   [11:0] trunc_ln46_5_fu_264_p1;
wire   [0:0] icmp_ln45_6_fu_276_p2;
wire   [11:0] trunc_ln46_6_fu_282_p1;
wire   [0:0] icmp_ln45_7_fu_294_p2;
wire   [11:0] trunc_ln46_7_fu_300_p1;
wire   [0:0] icmp_ln45_8_fu_312_p2;
wire   [11:0] trunc_ln46_8_fu_318_p1;
wire   [0:0] icmp_ln45_9_fu_330_p2;
wire   [11:0] trunc_ln46_9_fu_336_p1;
wire   [0:0] icmp_ln45_10_fu_348_p2;
wire   [11:0] trunc_ln46_10_fu_354_p1;
wire   [0:0] icmp_ln45_11_fu_366_p2;
wire   [11:0] trunc_ln46_11_fu_372_p1;
wire   [0:0] icmp_ln45_12_fu_384_p2;
wire   [11:0] trunc_ln46_12_fu_390_p1;
wire   [0:0] icmp_ln45_13_fu_402_p2;
wire   [11:0] trunc_ln46_13_fu_408_p1;
wire   [0:0] icmp_ln45_14_fu_420_p2;
wire   [11:0] trunc_ln46_14_fu_426_p1;
wire   [0:0] icmp_ln45_15_fu_438_p2;
wire   [11:0] trunc_ln46_15_fu_444_p1;
wire   [0:0] icmp_ln45_16_fu_456_p2;
wire   [11:0] trunc_ln46_16_fu_462_p1;
wire   [0:0] icmp_ln45_17_fu_474_p2;
wire   [11:0] trunc_ln46_17_fu_480_p1;
wire   [0:0] icmp_ln45_18_fu_492_p2;
wire   [11:0] trunc_ln46_18_fu_498_p1;
wire   [11:0] select_ln45_fu_178_p3;
wire   [11:0] select_ln45_1_fu_196_p3;
wire   [11:0] select_ln45_2_fu_214_p3;
wire   [11:0] select_ln45_3_fu_232_p3;
wire   [11:0] select_ln45_4_fu_250_p3;
wire   [11:0] select_ln45_5_fu_268_p3;
wire   [11:0] select_ln45_6_fu_286_p3;
wire   [11:0] select_ln45_7_fu_304_p3;
wire   [11:0] select_ln45_8_fu_322_p3;
wire   [11:0] select_ln45_9_fu_340_p3;
wire   [11:0] select_ln45_10_fu_358_p3;
wire   [11:0] select_ln45_11_fu_376_p3;
wire   [11:0] select_ln45_12_fu_394_p3;
wire   [11:0] select_ln45_13_fu_412_p3;
wire   [11:0] select_ln45_14_fu_430_p3;
wire   [11:0] select_ln45_15_fu_448_p3;
wire   [11:0] select_ln45_16_fu_466_p3;
wire   [11:0] select_ln45_17_fu_484_p3;
wire   [11:0] select_ln45_18_fu_502_p3;

assign ap_ready = 1'b1;

assign select_ln45_10_fu_358_p3 = ((icmp_ln45_10_fu_348_p2[0:0] == 1'b1) ? trunc_ln46_10_fu_354_p1 : 12'd0);

assign select_ln45_11_fu_376_p3 = ((icmp_ln45_11_fu_366_p2[0:0] == 1'b1) ? trunc_ln46_11_fu_372_p1 : 12'd0);

assign select_ln45_12_fu_394_p3 = ((icmp_ln45_12_fu_384_p2[0:0] == 1'b1) ? trunc_ln46_12_fu_390_p1 : 12'd0);

assign select_ln45_13_fu_412_p3 = ((icmp_ln45_13_fu_402_p2[0:0] == 1'b1) ? trunc_ln46_13_fu_408_p1 : 12'd0);

assign select_ln45_14_fu_430_p3 = ((icmp_ln45_14_fu_420_p2[0:0] == 1'b1) ? trunc_ln46_14_fu_426_p1 : 12'd0);

assign select_ln45_15_fu_448_p3 = ((icmp_ln45_15_fu_438_p2[0:0] == 1'b1) ? trunc_ln46_15_fu_444_p1 : 12'd0);

assign select_ln45_16_fu_466_p3 = ((icmp_ln45_16_fu_456_p2[0:0] == 1'b1) ? trunc_ln46_16_fu_462_p1 : 12'd0);

assign select_ln45_17_fu_484_p3 = ((icmp_ln45_17_fu_474_p2[0:0] == 1'b1) ? trunc_ln46_17_fu_480_p1 : 12'd0);

assign select_ln45_18_fu_502_p3 = ((icmp_ln45_18_fu_492_p2[0:0] == 1'b1) ? trunc_ln46_18_fu_498_p1 : 12'd0);

assign select_ln45_1_fu_196_p3 = ((icmp_ln45_1_fu_186_p2[0:0] == 1'b1) ? trunc_ln46_1_fu_192_p1 : 12'd0);

assign select_ln45_2_fu_214_p3 = ((icmp_ln45_2_fu_204_p2[0:0] == 1'b1) ? trunc_ln46_2_fu_210_p1 : 12'd0);

assign select_ln45_3_fu_232_p3 = ((icmp_ln45_3_fu_222_p2[0:0] == 1'b1) ? trunc_ln46_3_fu_228_p1 : 12'd0);

assign select_ln45_4_fu_250_p3 = ((icmp_ln45_4_fu_240_p2[0:0] == 1'b1) ? trunc_ln46_4_fu_246_p1 : 12'd0);

assign select_ln45_5_fu_268_p3 = ((icmp_ln45_5_fu_258_p2[0:0] == 1'b1) ? trunc_ln46_5_fu_264_p1 : 12'd0);

assign select_ln45_6_fu_286_p3 = ((icmp_ln45_6_fu_276_p2[0:0] == 1'b1) ? trunc_ln46_6_fu_282_p1 : 12'd0);

assign select_ln45_7_fu_304_p3 = ((icmp_ln45_7_fu_294_p2[0:0] == 1'b1) ? trunc_ln46_7_fu_300_p1 : 12'd0);

assign select_ln45_8_fu_322_p3 = ((icmp_ln45_8_fu_312_p2[0:0] == 1'b1) ? trunc_ln46_8_fu_318_p1 : 12'd0);

assign select_ln45_9_fu_340_p3 = ((icmp_ln45_9_fu_330_p2[0:0] == 1'b1) ? trunc_ln46_9_fu_336_p1 : 12'd0);

assign select_ln45_fu_178_p3 = ((icmp_ln45_fu_168_p2[0:0] == 1'b1) ? trunc_ln46_fu_174_p1 : 12'd0);

assign trunc_ln46_10_fu_354_p1 = data_25_val[11:0];

assign trunc_ln46_11_fu_372_p1 = data_33_val[11:0];

assign trunc_ln46_12_fu_390_p1 = data_36_val[11:0];

assign trunc_ln46_13_fu_408_p1 = data_37_val[11:0];

assign trunc_ln46_14_fu_426_p1 = data_38_val[11:0];

assign trunc_ln46_15_fu_444_p1 = data_46_val[11:0];

assign trunc_ln46_16_fu_462_p1 = data_50_val[11:0];

assign trunc_ln46_17_fu_480_p1 = data_57_val[11:0];

assign trunc_ln46_18_fu_498_p1 = data_61_val[11:0];

assign trunc_ln46_1_fu_192_p1 = data_3_val[11:0];

assign trunc_ln46_2_fu_210_p1 = data_5_val[11:0];

assign trunc_ln46_3_fu_228_p1 = data_6_val[11:0];

assign trunc_ln46_4_fu_246_p1 = data_7_val[11:0];

assign trunc_ln46_5_fu_264_p1 = data_10_val[11:0];

assign trunc_ln46_6_fu_282_p1 = data_14_val[11:0];

assign trunc_ln46_7_fu_300_p1 = data_17_val[11:0];

assign trunc_ln46_8_fu_318_p1 = data_19_val[11:0];

assign trunc_ln46_9_fu_336_p1 = data_20_val[11:0];

assign trunc_ln46_fu_174_p1 = data_2_val[11:0];

assign ap_return_0 = select_ln45_fu_178_p3;

assign ap_return_1 = select_ln45_1_fu_196_p3;

assign ap_return_10 = select_ln45_10_fu_358_p3;

assign ap_return_11 = select_ln45_11_fu_376_p3;

assign ap_return_12 = select_ln45_12_fu_394_p3;

assign ap_return_13 = select_ln45_13_fu_412_p3;

assign ap_return_14 = select_ln45_14_fu_430_p3;

assign ap_return_15 = select_ln45_15_fu_448_p3;

assign ap_return_16 = select_ln45_16_fu_466_p3;

assign ap_return_17 = select_ln45_17_fu_484_p3;

assign ap_return_18 = select_ln45_18_fu_502_p3;

assign ap_return_2 = select_ln45_2_fu_214_p3;

assign ap_return_3 = select_ln45_3_fu_232_p3;

assign ap_return_4 = select_ln45_4_fu_250_p3;

assign ap_return_5 = select_ln45_5_fu_268_p3;

assign ap_return_6 = select_ln45_6_fu_286_p3;

assign ap_return_7 = select_ln45_7_fu_304_p3;

assign ap_return_8 = select_ln45_8_fu_322_p3;

assign ap_return_9 = select_ln45_9_fu_340_p3;

assign icmp_ln45_10_fu_348_p2 = (($signed(data_25_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_11_fu_366_p2 = (($signed(data_33_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_12_fu_384_p2 = (($signed(data_36_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_13_fu_402_p2 = (($signed(data_37_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_14_fu_420_p2 = (($signed(data_38_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_15_fu_438_p2 = (($signed(data_46_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_16_fu_456_p2 = (($signed(data_50_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_17_fu_474_p2 = (($signed(data_57_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_18_fu_492_p2 = (($signed(data_61_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_1_fu_186_p2 = (($signed(data_3_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_2_fu_204_p2 = (($signed(data_5_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_3_fu_222_p2 = (($signed(data_6_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_4_fu_240_p2 = (($signed(data_7_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_5_fu_258_p2 = (($signed(data_10_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_6_fu_276_p2 = (($signed(data_14_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_7_fu_294_p2 = (($signed(data_17_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_8_fu_312_p2 = (($signed(data_19_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_9_fu_330_p2 = (($signed(data_20_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_168_p2 = (($signed(data_2_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_13_8_5_3_0_ap_ufixed_12_7_5_3_0_ReLU_config6_s
