-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_13_9_5_3_0_ap_ufixed_11_7_5_3_0_ReLU_config16_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_17_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_18_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_20_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_21_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_23_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_24_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_26_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_27_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_28_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_29_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_30_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_31_val : IN STD_LOGIC_VECTOR (12 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (10 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_relu_ap_fixed_13_9_5_3_0_ap_ufixed_11_7_5_3_0_ReLU_config16_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_fu_246_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_1_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_1_fu_264_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_2_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_2_fu_282_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_3_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_3_fu_300_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_4_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_4_fu_318_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_5_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_5_fu_336_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_6_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_6_fu_354_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_7_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_7_fu_372_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_8_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_8_fu_390_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_9_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_9_fu_408_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_10_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_10_fu_426_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_11_fu_438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_11_fu_444_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_12_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_12_fu_462_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_13_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_13_fu_480_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_14_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_14_fu_498_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_15_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_15_fu_516_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_16_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_16_fu_534_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_17_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_17_fu_552_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_18_fu_564_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_18_fu_570_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_19_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_19_fu_588_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_20_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_20_fu_606_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_21_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_21_fu_624_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_22_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_22_fu_642_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_23_fu_654_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_23_fu_660_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_24_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_24_fu_678_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_25_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_25_fu_696_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_26_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_26_fu_714_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln45_27_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_27_fu_732_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_fu_250_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_1_fu_268_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_2_fu_286_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_3_fu_304_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_4_fu_322_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_5_fu_340_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_6_fu_358_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_7_fu_376_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_8_fu_394_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_9_fu_412_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_10_fu_430_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_11_fu_448_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_12_fu_466_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_13_fu_484_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_14_fu_502_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_15_fu_520_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_16_fu_538_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_17_fu_556_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_18_fu_574_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_19_fu_592_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_20_fu_610_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_21_fu_628_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_22_fu_646_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_23_fu_664_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_24_fu_682_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_25_fu_700_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_26_fu_718_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln45_27_fu_736_p3 : STD_LOGIC_VECTOR (10 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln45_fu_250_p3;
    ap_return_1 <= select_ln45_1_fu_268_p3;
    ap_return_10 <= select_ln45_10_fu_430_p3;
    ap_return_11 <= select_ln45_11_fu_448_p3;
    ap_return_12 <= select_ln45_12_fu_466_p3;
    ap_return_13 <= select_ln45_13_fu_484_p3;
    ap_return_14 <= select_ln45_14_fu_502_p3;
    ap_return_15 <= select_ln45_15_fu_520_p3;
    ap_return_16 <= select_ln45_16_fu_538_p3;
    ap_return_17 <= select_ln45_17_fu_556_p3;
    ap_return_18 <= select_ln45_18_fu_574_p3;
    ap_return_19 <= select_ln45_19_fu_592_p3;
    ap_return_2 <= select_ln45_2_fu_286_p3;
    ap_return_20 <= select_ln45_20_fu_610_p3;
    ap_return_21 <= select_ln45_21_fu_628_p3;
    ap_return_22 <= select_ln45_22_fu_646_p3;
    ap_return_23 <= select_ln45_23_fu_664_p3;
    ap_return_24 <= select_ln45_24_fu_682_p3;
    ap_return_25 <= select_ln45_25_fu_700_p3;
    ap_return_26 <= select_ln45_26_fu_718_p3;
    ap_return_27 <= select_ln45_27_fu_736_p3;
    ap_return_3 <= select_ln45_3_fu_304_p3;
    ap_return_4 <= select_ln45_4_fu_322_p3;
    ap_return_5 <= select_ln45_5_fu_340_p3;
    ap_return_6 <= select_ln45_6_fu_358_p3;
    ap_return_7 <= select_ln45_7_fu_376_p3;
    ap_return_8 <= select_ln45_8_fu_394_p3;
    ap_return_9 <= select_ln45_9_fu_412_p3;
    icmp_ln45_10_fu_420_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_11_fu_438_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_12_fu_456_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_13_fu_474_p2 <= "1" when (signed(data_16_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_14_fu_492_p2 <= "1" when (signed(data_17_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_15_fu_510_p2 <= "1" when (signed(data_18_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_16_fu_528_p2 <= "1" when (signed(data_20_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_17_fu_546_p2 <= "1" when (signed(data_21_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_18_fu_564_p2 <= "1" when (signed(data_22_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_19_fu_582_p2 <= "1" when (signed(data_23_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_1_fu_258_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_20_fu_600_p2 <= "1" when (signed(data_24_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_21_fu_618_p2 <= "1" when (signed(data_25_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_22_fu_636_p2 <= "1" when (signed(data_26_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_23_fu_654_p2 <= "1" when (signed(data_27_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_24_fu_672_p2 <= "1" when (signed(data_28_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_25_fu_690_p2 <= "1" when (signed(data_29_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_26_fu_708_p2 <= "1" when (signed(data_30_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_27_fu_726_p2 <= "1" when (signed(data_31_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_2_fu_276_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_3_fu_294_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_4_fu_312_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_5_fu_330_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_6_fu_348_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_7_fu_366_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_8_fu_384_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_9_fu_402_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_fu_240_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv13_0)) else "0";
    select_ln45_10_fu_430_p3 <= 
        trunc_ln46_10_fu_426_p1 when (icmp_ln45_10_fu_420_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_11_fu_448_p3 <= 
        trunc_ln46_11_fu_444_p1 when (icmp_ln45_11_fu_438_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_12_fu_466_p3 <= 
        trunc_ln46_12_fu_462_p1 when (icmp_ln45_12_fu_456_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_13_fu_484_p3 <= 
        trunc_ln46_13_fu_480_p1 when (icmp_ln45_13_fu_474_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_14_fu_502_p3 <= 
        trunc_ln46_14_fu_498_p1 when (icmp_ln45_14_fu_492_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_15_fu_520_p3 <= 
        trunc_ln46_15_fu_516_p1 when (icmp_ln45_15_fu_510_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_16_fu_538_p3 <= 
        trunc_ln46_16_fu_534_p1 when (icmp_ln45_16_fu_528_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_17_fu_556_p3 <= 
        trunc_ln46_17_fu_552_p1 when (icmp_ln45_17_fu_546_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_18_fu_574_p3 <= 
        trunc_ln46_18_fu_570_p1 when (icmp_ln45_18_fu_564_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_19_fu_592_p3 <= 
        trunc_ln46_19_fu_588_p1 when (icmp_ln45_19_fu_582_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_1_fu_268_p3 <= 
        trunc_ln46_1_fu_264_p1 when (icmp_ln45_1_fu_258_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_20_fu_610_p3 <= 
        trunc_ln46_20_fu_606_p1 when (icmp_ln45_20_fu_600_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_21_fu_628_p3 <= 
        trunc_ln46_21_fu_624_p1 when (icmp_ln45_21_fu_618_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_22_fu_646_p3 <= 
        trunc_ln46_22_fu_642_p1 when (icmp_ln45_22_fu_636_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_23_fu_664_p3 <= 
        trunc_ln46_23_fu_660_p1 when (icmp_ln45_23_fu_654_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_24_fu_682_p3 <= 
        trunc_ln46_24_fu_678_p1 when (icmp_ln45_24_fu_672_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_25_fu_700_p3 <= 
        trunc_ln46_25_fu_696_p1 when (icmp_ln45_25_fu_690_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_26_fu_718_p3 <= 
        trunc_ln46_26_fu_714_p1 when (icmp_ln45_26_fu_708_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_27_fu_736_p3 <= 
        trunc_ln46_27_fu_732_p1 when (icmp_ln45_27_fu_726_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_2_fu_286_p3 <= 
        trunc_ln46_2_fu_282_p1 when (icmp_ln45_2_fu_276_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_3_fu_304_p3 <= 
        trunc_ln46_3_fu_300_p1 when (icmp_ln45_3_fu_294_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_4_fu_322_p3 <= 
        trunc_ln46_4_fu_318_p1 when (icmp_ln45_4_fu_312_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_5_fu_340_p3 <= 
        trunc_ln46_5_fu_336_p1 when (icmp_ln45_5_fu_330_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_6_fu_358_p3 <= 
        trunc_ln46_6_fu_354_p1 when (icmp_ln45_6_fu_348_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_7_fu_376_p3 <= 
        trunc_ln46_7_fu_372_p1 when (icmp_ln45_7_fu_366_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_8_fu_394_p3 <= 
        trunc_ln46_8_fu_390_p1 when (icmp_ln45_8_fu_384_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_9_fu_412_p3 <= 
        trunc_ln46_9_fu_408_p1 when (icmp_ln45_9_fu_402_p2(0) = '1') else 
        ap_const_lv11_0;
    select_ln45_fu_250_p3 <= 
        trunc_ln46_fu_246_p1 when (icmp_ln45_fu_240_p2(0) = '1') else 
        ap_const_lv11_0;
    trunc_ln46_10_fu_426_p1 <= data_12_val(11 - 1 downto 0);
    trunc_ln46_11_fu_444_p1 <= data_14_val(11 - 1 downto 0);
    trunc_ln46_12_fu_462_p1 <= data_15_val(11 - 1 downto 0);
    trunc_ln46_13_fu_480_p1 <= data_16_val(11 - 1 downto 0);
    trunc_ln46_14_fu_498_p1 <= data_17_val(11 - 1 downto 0);
    trunc_ln46_15_fu_516_p1 <= data_18_val(11 - 1 downto 0);
    trunc_ln46_16_fu_534_p1 <= data_20_val(11 - 1 downto 0);
    trunc_ln46_17_fu_552_p1 <= data_21_val(11 - 1 downto 0);
    trunc_ln46_18_fu_570_p1 <= data_22_val(11 - 1 downto 0);
    trunc_ln46_19_fu_588_p1 <= data_23_val(11 - 1 downto 0);
    trunc_ln46_1_fu_264_p1 <= data_1_val(11 - 1 downto 0);
    trunc_ln46_20_fu_606_p1 <= data_24_val(11 - 1 downto 0);
    trunc_ln46_21_fu_624_p1 <= data_25_val(11 - 1 downto 0);
    trunc_ln46_22_fu_642_p1 <= data_26_val(11 - 1 downto 0);
    trunc_ln46_23_fu_660_p1 <= data_27_val(11 - 1 downto 0);
    trunc_ln46_24_fu_678_p1 <= data_28_val(11 - 1 downto 0);
    trunc_ln46_25_fu_696_p1 <= data_29_val(11 - 1 downto 0);
    trunc_ln46_26_fu_714_p1 <= data_30_val(11 - 1 downto 0);
    trunc_ln46_27_fu_732_p1 <= data_31_val(11 - 1 downto 0);
    trunc_ln46_2_fu_282_p1 <= data_2_val(11 - 1 downto 0);
    trunc_ln46_3_fu_300_p1 <= data_3_val(11 - 1 downto 0);
    trunc_ln46_4_fu_318_p1 <= data_4_val(11 - 1 downto 0);
    trunc_ln46_5_fu_336_p1 <= data_5_val(11 - 1 downto 0);
    trunc_ln46_6_fu_354_p1 <= data_7_val(11 - 1 downto 0);
    trunc_ln46_7_fu_372_p1 <= data_9_val(11 - 1 downto 0);
    trunc_ln46_8_fu_390_p1 <= data_10_val(11 - 1 downto 0);
    trunc_ln46_9_fu_408_p1 <= data_11_val(11 - 1 downto 0);
    trunc_ln46_fu_246_p1 <= data_0_val(11 - 1 downto 0);
end behav;
