// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_ufixed_9_7_5_3_0_ap_fixed_13_11_5_3_0_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_3_val,
        data_6_val,
        data_10_val,
        data_12_val,
        data_21_val,
        data_22_val,
        data_24_val,
        data_27_val,
        data_29_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [8:0] data_3_val;
input  [7:0] data_6_val;
input  [8:0] data_10_val;
input  [6:0] data_12_val;
input  [7:0] data_21_val;
input  [6:0] data_22_val;
input  [8:0] data_24_val;
input  [6:0] data_27_val;
input  [6:0] data_29_val;
output  [12:0] ap_return_0;
output  [12:0] ap_return_1;
output  [12:0] ap_return_2;
output  [12:0] ap_return_3;
output  [12:0] ap_return_4;
output  [12:0] ap_return_5;
output  [12:0] ap_return_6;
output  [12:0] ap_return_7;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [12:0] mult_5_fu_281_p2;
reg   [12:0] mult_5_reg_846;
wire    ap_block_pp0_stage0_11001;
wire   [14:0] mult_36_fu_274_p2;
reg   [14:0] mult_36_reg_850;
reg   [6:0] data_29_val_read_reg_2561;
reg   [6:0] data_27_val_read_reg_2570;
reg   [8:0] data_24_val_read_reg_2580;
reg   [6:0] data_22_val_read_reg_2590;
reg   [7:0] data_21_val_read_reg_2600;
reg   [6:0] data_12_val_read_reg_2609;
reg   [8:0] data_10_val_read_reg_2618;
reg   [7:0] data_6_val_read_reg_2627;
reg   [8:0] data_3_val_read_reg_2637;
wire   [6:0] mult_36_fu_274_p0;
wire  signed [7:0] mult_36_fu_274_p1;
wire    ap_block_pp0_stage0;
wire   [7:0] mult_5_fu_281_p0;
wire   [5:0] mult_5_fu_281_p1;
wire   [9:0] tmp_48_fu_875_p3;
wire   [11:0] p_shl1_fu_868_p3;
wire   [11:0] zext_ln73_1_fu_882_p1;
wire   [11:0] mult_fu_886_p2;
wire   [10:0] zext_ln73_2_fu_896_p1;
wire   [10:0] mult_1_fu_900_p2;
wire   [12:0] mult_2_fu_910_p3;
wire   [13:0] tmp_49_fu_921_p3;
wire   [10:0] tmp_50_fu_932_p3;
wire   [14:0] zext_ln73_4_fu_939_p1;
wire   [14:0] zext_ln73_3_fu_928_p1;
wire   [14:0] mult_4_fu_949_p2;
wire   [11:0] tmp_51_fu_969_p3;
wire   [12:0] zext_ln73_8_fu_976_p1;
wire   [12:0] mult_6_fu_980_p2;
wire   [9:0] mult_7_fu_990_p3;
wire   [10:0] tmp_52_fu_1001_p3;
wire   [8:0] tmp_53_fu_1012_p3;
wire   [11:0] zext_ln73_9_fu_1008_p1;
wire   [11:0] zext_ln73_10_fu_1019_p1;
wire   [11:0] mult_8_fu_1023_p2;
wire   [11:0] mult_9_fu_1033_p2;
wire   [12:0] mult_15_fu_1050_p3;
wire   [14:0] p_shl2_fu_1043_p3;
wire   [14:0] zext_ln73_11_fu_1057_p1;
wire   [14:0] mult_10_fu_1061_p2;
wire   [13:0] tmp_55_fu_1071_p3;
wire   [14:0] zext_ln73_12_fu_1078_p1;
wire   [14:0] mult_11_fu_1082_p2;
wire   [11:0] tmp_56_fu_1092_p3;
wire   [9:0] tmp_57_fu_1103_p3;
wire   [12:0] zext_ln73_15_fu_1110_p1;
wire   [12:0] zext_ln73_13_fu_1099_p1;
wire   [12:0] mult_12_fu_1114_p2;
wire   [13:0] zext_ln73_16_fu_1124_p1;
wire   [13:0] mult_13_fu_1128_p2;
wire   [15:0] zext_ln73_17_fu_1138_p1;
wire   [15:0] mult_14_fu_1142_p2;
wire   [8:0] tmp_58_fu_1162_p3;
wire   [11:0] p_shl3_fu_1155_p3;
wire   [11:0] zext_ln73_18_fu_1169_p1;
wire   [11:0] mult_16_fu_1173_p2;
wire   [13:0] zext_ln73_20_fu_1183_p1;
wire   [9:0] tmp_59_fu_1193_p3;
wire   [13:0] sub_ln73_fu_1187_p2;
wire   [13:0] zext_ln73_21_fu_1200_p1;
wire   [12:0] zext_ln73_22_fu_1210_p1;
wire   [12:0] zext_ln73_23_fu_1214_p1;
wire   [10:0] zext_ln73_24_fu_1224_p1;
wire   [10:0] mult_19_fu_1228_p2;
wire   [10:0] tmp_60_fu_1238_p3;
wire   [12:0] zext_ln73_25_fu_1245_p1;
wire   [12:0] sub_ln73_3_fu_1249_p2;
wire   [10:0] tmp_61_fu_1264_p3;
wire   [11:0] zext_ln73_26_fu_1271_p1;
wire   [11:0] mult_21_fu_1275_p2;
wire   [11:0] mult_22_fu_1285_p3;
wire   [8:0] tmp_62_fu_1296_p3;
wire   [11:0] zext_ln73_28_fu_1303_p1;
wire   [11:0] mult_23_fu_1307_p2;
wire   [9:0] tmp_63_fu_1317_p3;
wire   [10:0] zext_ln73_29_fu_1324_p1;
wire   [10:0] mult_24_fu_1328_p2;
wire   [15:0] tmp_64_fu_1338_p3;
wire   [11:0] tmp_65_fu_1356_p3;
wire   [13:0] p_shl4_fu_1349_p3;
wire   [13:0] zext_ln73_34_fu_1363_p1;
wire   [13:0] mult_25_fu_1367_p2;
wire   [10:0] mult_26_fu_1377_p3;
wire   [12:0] tmp_66_fu_1388_p3;
wire   [9:0] mult_28_fu_1399_p3;
wire   [13:0] zext_ln73_35_fu_1395_p1;
wire   [13:0] zext_ln73_36_fu_1406_p1;
wire   [13:0] mult_27_fu_1410_p2;
wire   [13:0] zext_ln17_11_fu_1384_p1;
wire   [17:0] tmp_68_fu_1434_p3;
wire   [9:0] tmp_69_fu_1452_p3;
wire   [12:0] p_shl5_fu_1445_p3;
wire   [12:0] zext_ln73_38_fu_1459_p1;
wire   [12:0] mult_30_fu_1463_p2;
wire   [11:0] mult_33_fu_1473_p3;
wire   [13:0] zext_ln73_39_fu_1480_p1;
wire   [13:0] sub_ln73_10_fu_1484_p2;
wire   [13:0] zext_ln73_40_fu_1490_p1;
wire   [14:0] tmp_71_fu_1500_p3;
wire   [15:0] zext_ln73_42_fu_1511_p1;
wire   [15:0] zext_ln73_41_fu_1507_p1;
wire   [13:0] p_shl6_fu_1525_p3;
wire   [13:0] mult_34_fu_1532_p2;
wire   [7:0] tmp_72_fu_1548_p3;
wire   [8:0] zext_ln73_43_fu_1555_p1;
wire   [8:0] mult_35_fu_1559_p2;
wire   [11:0] tmp_73_fu_1569_p3;
wire   [12:0] zext_ln73_45_fu_1580_p1;
wire   [12:0] zext_ln73_44_fu_1576_p1;
wire   [8:0] tmp_74_fu_1590_p3;
wire   [9:0] zext_ln73_46_fu_1597_p1;
wire   [9:0] mult_38_fu_1601_p2;
wire   [10:0] p_shl7_fu_1611_p3;
wire   [10:0] zext_ln73_47_fu_1618_p1;
wire   [10:0] mult_39_fu_1622_p2;
wire   [11:0] zext_ln73_48_fu_1632_p1;
wire   [11:0] zext_ln73_27_fu_1542_p1;
wire   [11:0] mult_40_fu_1636_p2;
wire   [12:0] zext_ln73_49_fu_1646_p1;
wire   [9:0] mult_44_fu_1666_p3;
wire   [11:0] p_shl8_fu_1659_p3;
wire   [11:0] zext_ln73_50_fu_1673_p1;
wire   [11:0] mult_42_fu_1677_p2;
wire   [10:0] tmp_76_fu_1687_p3;
wire   [11:0] zext_ln73_51_fu_1694_p1;
wire   [11:0] mult_43_fu_1698_p2;
wire   [8:0] tmp_77_fu_1708_p3;
wire   [10:0] zext_ln17_21_fu_1715_p1;
wire   [8:0] zext_ln73_19_fu_1261_p1;
wire   [8:0] zext_ln73_14_fu_1152_p1;
wire   [8:0] tmp_fu_1725_p2;
wire   [10:0] tmp1_fu_1731_p3;
wire  signed [13:0] sext_ln17_2_fu_1039_p1;
wire   [13:0] add_ln58_fu_1743_p2;
wire  signed [15:0] sext_ln58_fu_1749_p1;
wire   [15:0] zext_ln17_2_fu_955_p1;
wire   [11:0] zext_ln17_14_fu_1424_p1;
wire   [11:0] zext_ln58_fu_1739_p1;
wire   [11:0] add_ln58_2_fu_1759_p2;
wire   [12:0] mult_41_fu_1650_p2;
wire   [12:0] add_ln58_3_fu_1769_p2;
wire   [12:0] zext_ln58_1_fu_1765_p1;
wire   [12:0] add_ln58_4_fu_1775_p2;
wire  signed [15:0] sext_ln58_1_fu_1781_p1;
wire   [15:0] add_ln58_1_fu_1753_p2;
wire   [15:0] tmp_78_fu_1791_p3;
wire   [16:0] p_shl24_fu_1799_p1;
wire   [16:0] tmp3_fu_1803_p2;
wire   [13:0] zext_ln17_fu_892_p1;
wire   [13:0] zext_ln17_3_fu_965_p1;
wire   [13:0] add_ln58_6_fu_1813_p2;
wire   [16:0] zext_ln17_6_fu_1067_p1;
wire   [16:0] zext_ln73_30_fu_1345_p1;
wire   [16:0] sub_ln58_fu_1823_p2;
wire   [16:0] zext_ln58_2_fu_1819_p1;
wire   [16:0] add_ln58_7_fu_1829_p2;
wire  signed [18:0] sext_ln58_2_fu_1809_p1;
wire   [18:0] zext_ln73_37_fu_1441_p1;
wire   [12:0] zext_ln17_20_fu_1683_p1;
wire   [12:0] add_ln58_8_fu_1845_p2;
wire  signed [12:0] sext_ln17_10_fu_1565_p1;
wire   [12:0] add_ln58_9_fu_1851_p2;
wire  signed [18:0] sext_ln58_4_fu_1857_p1;
wire   [18:0] sub_ln58_1_fu_1839_p2;
wire   [18:0] add_ln58_10_fu_1861_p2;
wire  signed [18:0] sext_ln58_3_fu_1835_p1;
wire  signed [13:0] sext_ln17_fu_906_p1;
wire  signed [13:0] sext_ln17_1_fu_986_p1;
wire   [13:0] add_ln58_12_fu_1873_p2;
wire   [12:0] zext_ln17_7_fu_1179_p1;
wire  signed [12:0] sext_ln17_8_fu_1281_p1;
wire   [12:0] add_ln58_13_fu_1883_p2;
wire  signed [15:0] sext_ln58_6_fu_1889_p1;
wire  signed [15:0] sext_ln17_3_fu_1088_p1;
wire   [15:0] add_ln58_14_fu_1893_p2;
wire  signed [15:0] sext_ln58_5_fu_1879_p1;
wire   [15:0] add_ln58_15_fu_1899_p2;
wire   [14:0] zext_ln17_10_fu_1373_p1;
wire   [14:0] zext_ln17_15_fu_1469_p1;
wire   [14:0] add_ln58_16_fu_1909_p2;
wire   [11:0] sub_ln58_2_fu_1919_p2;
wire  signed [14:0] sext_ln58_8_fu_1925_p1;
wire   [14:0] add_ln58_17_fu_1929_p2;
wire  signed [15:0] sext_ln58_9_fu_1935_p1;
wire   [15:0] zext_ln58_3_fu_1915_p1;
wire   [15:0] add_ln58_18_fu_1939_p2;
wire  signed [16:0] sext_ln58_10_fu_1945_p1;
wire  signed [16:0] sext_ln58_7_fu_1905_p1;
wire   [9:0] zext_ln73_6_fu_962_p1;
wire   [9:0] zext_ln73_fu_865_p1;
wire   [9:0] tmp4_fu_1955_p2;
wire   [13:0] tmp_79_fu_1961_p3;
wire   [11:0] tmp_80_fu_1973_p3;
wire   [14:0] p_shl23_fu_1981_p1;
wire   [14:0] p_shl21_fu_1969_p1;
wire  signed [14:0] sext_ln17_4_fu_1120_p1;
wire   [14:0] tmp5_fu_1985_p2;
wire   [14:0] add_ln58_20_fu_1991_p2;
wire   [13:0] mult_17_fu_1204_p2;
wire   [13:0] zext_ln17_8_fu_1292_p1;
wire   [13:0] add_ln58_21_fu_2001_p2;
wire  signed [15:0] sext_ln58_12_fu_2007_p1;
wire  signed [15:0] sext_ln58_11_fu_1997_p1;
wire   [13:0] mult_31_fu_1494_p2;
wire   [11:0] add_ln58_24_fu_2023_p2;
wire   [12:0] zext_ln58_4_fu_2029_p1;
wire   [12:0] mult_37_fu_1584_p2;
wire   [12:0] add_ln58_25_fu_2033_p2;
wire  signed [13:0] sext_ln58_13_fu_2039_p1;
wire   [13:0] add_ln58_23_fu_2017_p2;
wire   [13:0] add_ln58_26_fu_2043_p2;
wire  signed [15:0] sext_ln58_14_fu_2049_p1;
wire   [15:0] add_ln58_22_fu_2011_p2;
wire   [14:0] tmp_81_fu_2059_p3;
wire   [12:0] tmp_82_fu_2071_p3;
wire   [15:0] p_shl20_fu_2079_p1;
wire   [15:0] p_shl19_fu_2067_p1;
wire  signed [15:0] sext_ln17_5_fu_1134_p1;
wire   [15:0] tmp7_fu_2083_p2;
wire   [12:0] mult_18_fu_1218_p2;
wire   [12:0] zext_ln17_9_fu_1313_p1;
wire   [12:0] add_ln58_29_fu_2095_p2;
wire   [15:0] zext_ln58_5_fu_2101_p1;
wire   [15:0] add_ln58_28_fu_2089_p2;
wire   [15:0] add_ln58_30_fu_2105_p2;
wire   [15:0] zext_ln17_12_fu_1416_p1;
wire   [15:0] mult_32_fu_1515_p2;
wire   [12:0] add_ln58_32_fu_2121_p2;
wire  signed [12:0] sext_ln17_11_fu_1607_p1;
wire   [12:0] add_ln58_33_fu_2127_p2;
wire   [15:0] zext_ln58_6_fu_2133_p1;
wire   [15:0] add_ln58_31_fu_2115_p2;
wire   [15:0] add_ln58_34_fu_2137_p2;
wire  signed [16:0] sext_ln58_16_fu_2143_p1;
wire  signed [16:0] sext_ln58_15_fu_2111_p1;
wire   [8:0] zext_ln73_33_fu_1656_p1;
wire   [8:0] tmp8_fu_2153_p2;
wire   [16:0] tmp_83_fu_2159_p3;
wire   [13:0] zext_ln17_1_fu_917_p1;
wire   [13:0] zext_ln17_4_fu_997_p1;
wire   [13:0] add_ln58_36_fu_2171_p2;
wire  signed [16:0] sext_ln17_6_fu_1148_p1;
wire  signed [16:0] sext_ln17_7_fu_1234_p1;
wire   [16:0] add_ln58_37_fu_2181_p2;
wire   [16:0] zext_ln58_7_fu_2177_p1;
wire   [16:0] add_ln58_38_fu_2187_p2;
wire   [18:0] zext_ln17_18_fu_1628_p1;
wire   [17:0] p_shl18_fu_2167_p1;
wire   [17:0] sub_ln58_4_fu_2203_p2;
wire  signed [18:0] sext_ln58_18_fu_2209_p1;
wire   [18:0] sub_ln58_3_fu_2197_p2;
wire   [18:0] add_ln58_39_fu_2213_p2;
wire  signed [18:0] sext_ln58_17_fu_2193_p1;
wire   [14:0] mult_3_fu_943_p2;
wire   [14:0] zext_ln17_5_fu_1029_p1;
wire   [14:0] add_ln58_41_fu_2225_p2;
wire   [12:0] mult_20_fu_1255_p2;
wire  signed [12:0] sext_ln17_9_fu_1334_p1;
wire   [12:0] add_ln58_42_fu_2235_p2;
wire  signed [16:0] sext_ln58_20_fu_2241_p1;
wire   [16:0] add_ln58_43_fu_2245_p2;
wire  signed [16:0] sext_ln58_19_fu_2231_p1;
wire   [12:0] zext_ln17_13_fu_1420_p1;
wire   [12:0] zext_ln17_16_fu_1521_p1;
wire   [12:0] add_ln58_45_fu_2257_p2;
wire   [10:0] sub_ln17_fu_1719_p2;
wire   [10:0] add_ln58_46_fu_2267_p2;
wire  signed [12:0] sext_ln58_21_fu_2273_p1;
wire   [12:0] zext_ln17_19_fu_1642_p1;
wire   [12:0] add_ln58_47_fu_2277_p2;
wire  signed [13:0] sext_ln58_22_fu_2283_p1;
wire   [13:0] zext_ln58_8_fu_2263_p1;
wire   [13:0] add_ln58_48_fu_2287_p2;
wire  signed [16:0] sext_ln58_23_fu_2293_p1;
wire   [16:0] add_ln58_44_fu_2251_p2;
wire   [8:0] zext_ln73_32_fu_1545_p1;
wire   [8:0] zext_ln73_5_fu_959_p1;
wire   [8:0] tmp10_fu_2303_p2;
wire   [16:0] tmp_84_fu_2309_p3;
wire   [17:0] p_shl_fu_2317_p1;
wire   [13:0] sub_ln58_5_fu_2327_p2;
wire   [13:0] mult_29_fu_1428_p2;
wire   [13:0] add_ln58_50_fu_2337_p2;
wire  signed [14:0] sext_ln58_25_fu_2343_p1;
wire  signed [14:0] sext_ln58_24_fu_2333_p1;
wire   [14:0] add_ln58_51_fu_2347_p2;
wire   [14:0] zext_ln17_17_fu_1538_p1;
wire  signed [14:0] sext_ln17_12_fu_1704_p1;
wire   [14:0] add_ln58_52_fu_2357_p2;
wire   [17:0] tmp11_fu_2321_p2;
wire   [9:0] tmp_s_fu_2367_p4;
wire   [0:0] tmp_85_fu_2377_p3;
wire   [17:0] or_ln_fu_2385_p5;
wire  signed [18:0] sext_ln58_28_fu_2397_p1;
wire  signed [18:0] sext_ln58_27_fu_2363_p1;
wire   [18:0] add_ln58_53_fu_2401_p2;
wire  signed [18:0] sext_ln58_26_fu_2353_p1;
wire   [18:0] add_ln58_11_fu_1867_p2;
wire   [16:0] add_ln58_19_fu_1949_p2;
wire   [10:0] trunc_ln111_1_fu_2423_p4;
wire   [15:0] add_ln58_27_fu_2053_p2;
wire   [9:0] trunc_ln111_2_fu_2437_p4;
wire   [16:0] add_ln58_35_fu_2147_p2;
wire   [10:0] trunc_ln111_3_fu_2451_p4;
wire   [18:0] add_ln58_40_fu_2219_p2;
wire   [16:0] add_ln58_49_fu_2297_p2;
wire   [10:0] trunc_ln111_5_fu_2475_p4;
wire   [15:0] add_ln58_5_fu_1785_p2;
wire   [9:0] trunc_ln111_6_fu_2489_p4;
wire   [18:0] add_ln58_54_fu_2407_p2;
wire  signed [12:0] sext_ln111_fu_2433_p1;
wire  signed [12:0] sext_ln111_1_fu_2447_p1;
wire  signed [12:0] sext_ln111_2_fu_2461_p1;
wire  signed [12:0] sext_ln111_3_fu_2485_p1;
wire  signed [12:0] sext_ln111_4_fu_2499_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [14:0] mult_36_fu_274_p00;
wire   [12:0] mult_5_fu_281_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

myproject_mul_7ns_8s_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_7ns_8s_15_1_1_U72(
    .din0(mult_36_fu_274_p0),
    .din1(mult_36_fu_274_p1),
    .dout(mult_36_fu_274_p2)
);

myproject_mul_8ns_6ns_13_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 13 ))
mul_8ns_6ns_13_1_1_U73(
    .din0(mult_5_fu_281_p0),
    .din1(mult_5_fu_281_p1),
    .dout(mult_5_fu_281_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_10_val_read_reg_2618 <= data_10_val;
        data_12_val_read_reg_2609 <= data_12_val;
        data_21_val_read_reg_2600 <= data_21_val;
        data_22_val_read_reg_2590 <= data_22_val;
        data_24_val_read_reg_2580 <= data_24_val;
        data_27_val_read_reg_2570 <= data_27_val;
        data_29_val_read_reg_2561 <= data_29_val;
        data_3_val_read_reg_2637 <= data_3_val;
        data_6_val_read_reg_2627 <= data_6_val;
        mult_36_reg_850 <= mult_36_fu_274_p2;
        mult_5_reg_846 <= mult_5_fu_281_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_10_fu_1861_p2 = ($signed(sext_ln58_4_fu_1857_p1) + $signed(sub_ln58_1_fu_1839_p2));

assign add_ln58_11_fu_1867_p2 = ($signed(add_ln58_10_fu_1861_p2) + $signed(sext_ln58_3_fu_1835_p1));

assign add_ln58_12_fu_1873_p2 = ($signed(sext_ln17_fu_906_p1) + $signed(sext_ln17_1_fu_986_p1));

assign add_ln58_13_fu_1883_p2 = ($signed(zext_ln17_7_fu_1179_p1) + $signed(sext_ln17_8_fu_1281_p1));

assign add_ln58_14_fu_1893_p2 = ($signed(sext_ln58_6_fu_1889_p1) + $signed(sext_ln17_3_fu_1088_p1));

assign add_ln58_15_fu_1899_p2 = ($signed(add_ln58_14_fu_1893_p2) + $signed(sext_ln58_5_fu_1879_p1));

assign add_ln58_16_fu_1909_p2 = (zext_ln17_10_fu_1373_p1 + zext_ln17_15_fu_1469_p1);

assign add_ln58_17_fu_1929_p2 = ($signed(sext_ln58_8_fu_1925_p1) + $signed(mult_36_reg_850));

assign add_ln58_18_fu_1939_p2 = ($signed(sext_ln58_9_fu_1935_p1) + $signed(zext_ln58_3_fu_1915_p1));

assign add_ln58_19_fu_1949_p2 = ($signed(sext_ln58_10_fu_1945_p1) + $signed(sext_ln58_7_fu_1905_p1));

assign add_ln58_1_fu_1753_p2 = ($signed(sext_ln58_fu_1749_p1) + $signed(zext_ln17_2_fu_955_p1));

assign add_ln58_20_fu_1991_p2 = ($signed(sext_ln17_4_fu_1120_p1) + $signed(tmp5_fu_1985_p2));

assign add_ln58_21_fu_2001_p2 = (mult_17_fu_1204_p2 + zext_ln17_8_fu_1292_p1);

assign add_ln58_22_fu_2011_p2 = ($signed(sext_ln58_12_fu_2007_p1) + $signed(sext_ln58_11_fu_1997_p1));

assign add_ln58_23_fu_2017_p2 = (zext_ln17_11_fu_1384_p1 + mult_31_fu_1494_p2);

assign add_ln58_24_fu_2023_p2 = (zext_ln73_50_fu_1673_p1 + 12'd1440);

assign add_ln58_25_fu_2033_p2 = (zext_ln58_4_fu_2029_p1 + mult_37_fu_1584_p2);

assign add_ln58_26_fu_2043_p2 = ($signed(sext_ln58_13_fu_2039_p1) + $signed(add_ln58_23_fu_2017_p2));

assign add_ln58_27_fu_2053_p2 = ($signed(sext_ln58_14_fu_2049_p1) + $signed(add_ln58_22_fu_2011_p2));

assign add_ln58_28_fu_2089_p2 = ($signed(sext_ln17_5_fu_1134_p1) + $signed(tmp7_fu_2083_p2));

assign add_ln58_29_fu_2095_p2 = (mult_18_fu_1218_p2 + zext_ln17_9_fu_1313_p1);

assign add_ln58_2_fu_1759_p2 = (zext_ln17_14_fu_1424_p1 + zext_ln58_fu_1739_p1);

assign add_ln58_30_fu_2105_p2 = (zext_ln58_5_fu_2101_p1 + add_ln58_28_fu_2089_p2);

assign add_ln58_31_fu_2115_p2 = (zext_ln17_12_fu_1416_p1 + mult_32_fu_1515_p2);

assign add_ln58_32_fu_2121_p2 = (zext_ln17_20_fu_1683_p1 + 13'd1120);

assign add_ln58_33_fu_2127_p2 = ($signed(add_ln58_32_fu_2121_p2) + $signed(sext_ln17_11_fu_1607_p1));

assign add_ln58_34_fu_2137_p2 = (zext_ln58_6_fu_2133_p1 + add_ln58_31_fu_2115_p2);

assign add_ln58_35_fu_2147_p2 = ($signed(sext_ln58_16_fu_2143_p1) + $signed(sext_ln58_15_fu_2111_p1));

assign add_ln58_36_fu_2171_p2 = (zext_ln17_1_fu_917_p1 + zext_ln17_4_fu_997_p1);

assign add_ln58_37_fu_2181_p2 = ($signed(sext_ln17_6_fu_1148_p1) + $signed(sext_ln17_7_fu_1234_p1));

assign add_ln58_38_fu_2187_p2 = (add_ln58_37_fu_2181_p2 + zext_ln58_7_fu_2177_p1);

assign add_ln58_39_fu_2213_p2 = ($signed(sext_ln58_18_fu_2209_p1) + $signed(sub_ln58_3_fu_2197_p2));

assign add_ln58_3_fu_1769_p2 = ($signed(mult_41_fu_1650_p2) + $signed(13'd7744));

assign add_ln58_40_fu_2219_p2 = ($signed(add_ln58_39_fu_2213_p2) + $signed(sext_ln58_17_fu_2193_p1));

assign add_ln58_41_fu_2225_p2 = (mult_3_fu_943_p2 + zext_ln17_5_fu_1029_p1);

assign add_ln58_42_fu_2235_p2 = ($signed(mult_20_fu_1255_p2) + $signed(sext_ln17_9_fu_1334_p1));

assign add_ln58_43_fu_2245_p2 = ($signed(sext_ln58_20_fu_2241_p1) + $signed(sext_ln17_6_fu_1148_p1));

assign add_ln58_44_fu_2251_p2 = ($signed(add_ln58_43_fu_2245_p2) + $signed(sext_ln58_19_fu_2231_p1));

assign add_ln58_45_fu_2257_p2 = (zext_ln17_13_fu_1420_p1 + zext_ln17_16_fu_1521_p1);

assign add_ln58_46_fu_2267_p2 = (sub_ln17_fu_1719_p2 + 11'd736);

assign add_ln58_47_fu_2277_p2 = ($signed(sext_ln58_21_fu_2273_p1) + $signed(zext_ln17_19_fu_1642_p1));

assign add_ln58_48_fu_2287_p2 = ($signed(sext_ln58_22_fu_2283_p1) + $signed(zext_ln58_8_fu_2263_p1));

assign add_ln58_49_fu_2297_p2 = ($signed(sext_ln58_23_fu_2293_p1) + $signed(add_ln58_44_fu_2251_p2));

assign add_ln58_4_fu_1775_p2 = (add_ln58_3_fu_1769_p2 + zext_ln58_1_fu_1765_p1);

assign add_ln58_50_fu_2337_p2 = (zext_ln17_8_fu_1292_p1 + mult_29_fu_1428_p2);

assign add_ln58_51_fu_2347_p2 = ($signed(sext_ln58_25_fu_2343_p1) + $signed(sext_ln58_24_fu_2333_p1));

assign add_ln58_52_fu_2357_p2 = ($signed(zext_ln17_17_fu_1538_p1) + $signed(sext_ln17_12_fu_1704_p1));

assign add_ln58_53_fu_2401_p2 = ($signed(sext_ln58_28_fu_2397_p1) + $signed(sext_ln58_27_fu_2363_p1));

assign add_ln58_54_fu_2407_p2 = ($signed(add_ln58_53_fu_2401_p2) + $signed(sext_ln58_26_fu_2353_p1));

assign add_ln58_5_fu_1785_p2 = ($signed(sext_ln58_1_fu_1781_p1) + $signed(add_ln58_1_fu_1753_p2));

assign add_ln58_6_fu_1813_p2 = (zext_ln17_fu_892_p1 + zext_ln17_3_fu_965_p1);

assign add_ln58_7_fu_1829_p2 = (sub_ln58_fu_1823_p2 + zext_ln58_2_fu_1819_p1);

assign add_ln58_8_fu_1845_p2 = ($signed(zext_ln17_20_fu_1683_p1) + $signed(13'd8000));

assign add_ln58_9_fu_1851_p2 = ($signed(add_ln58_8_fu_1845_p2) + $signed(sext_ln17_10_fu_1565_p1));

assign add_ln58_fu_1743_p2 = ($signed(sext_ln17_2_fu_1039_p1) + $signed(zext_ln73_16_fu_1124_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = {{add_ln58_11_fu_1867_p2[18:6]}};

assign ap_return_1 = sext_ln111_fu_2433_p1;

assign ap_return_2 = sext_ln111_1_fu_2447_p1;

assign ap_return_3 = sext_ln111_2_fu_2461_p1;

assign ap_return_4 = {{add_ln58_40_fu_2219_p2[18:6]}};

assign ap_return_5 = sext_ln111_3_fu_2485_p1;

assign ap_return_6 = sext_ln111_4_fu_2499_p1;

assign ap_return_7 = {{add_ln58_54_fu_2407_p2[18:6]}};

assign mult_10_fu_1061_p2 = (p_shl2_fu_1043_p3 - zext_ln73_11_fu_1057_p1);

assign mult_11_fu_1082_p2 = (15'd0 - zext_ln73_12_fu_1078_p1);

assign mult_12_fu_1114_p2 = (zext_ln73_15_fu_1110_p1 - zext_ln73_13_fu_1099_p1);

assign mult_13_fu_1128_p2 = (14'd0 - zext_ln73_16_fu_1124_p1);

assign mult_14_fu_1142_p2 = (16'd0 - zext_ln73_17_fu_1138_p1);

assign mult_15_fu_1050_p3 = {{data_10_val_read_reg_2618}, {4'd0}};

assign mult_16_fu_1173_p2 = (p_shl3_fu_1155_p3 - zext_ln73_18_fu_1169_p1);

assign mult_17_fu_1204_p2 = (sub_ln73_fu_1187_p2 - zext_ln73_21_fu_1200_p1);

assign mult_18_fu_1218_p2 = (zext_ln73_22_fu_1210_p1 + zext_ln73_23_fu_1214_p1);

assign mult_19_fu_1228_p2 = (11'd0 - zext_ln73_24_fu_1224_p1);

assign mult_1_fu_900_p2 = (11'd0 - zext_ln73_2_fu_896_p1);

assign mult_20_fu_1255_p2 = (sub_ln73_3_fu_1249_p2 - zext_ln73_23_fu_1214_p1);

assign mult_21_fu_1275_p2 = (12'd0 - zext_ln73_26_fu_1271_p1);

assign mult_22_fu_1285_p3 = {{data_21_val_read_reg_2600}, {4'd0}};

assign mult_23_fu_1307_p2 = (zext_ln73_26_fu_1271_p1 + zext_ln73_28_fu_1303_p1);

assign mult_24_fu_1328_p2 = (11'd0 - zext_ln73_29_fu_1324_p1);

assign mult_25_fu_1367_p2 = (p_shl4_fu_1349_p3 - zext_ln73_34_fu_1363_p1);

assign mult_26_fu_1377_p3 = {{data_22_val_read_reg_2590}, {4'd0}};

assign mult_27_fu_1410_p2 = (zext_ln73_35_fu_1395_p1 + zext_ln73_36_fu_1406_p1);

assign mult_28_fu_1399_p3 = {{data_22_val_read_reg_2590}, {3'd0}};

assign mult_29_fu_1428_p2 = (zext_ln17_11_fu_1384_p1 - zext_ln73_35_fu_1395_p1);

assign mult_2_fu_910_p3 = {{data_3_val_read_reg_2637}, {4'd0}};

assign mult_30_fu_1463_p2 = (p_shl5_fu_1445_p3 - zext_ln73_38_fu_1459_p1);

assign mult_31_fu_1494_p2 = (sub_ln73_10_fu_1484_p2 - zext_ln73_40_fu_1490_p1);

assign mult_32_fu_1515_p2 = (zext_ln73_42_fu_1511_p1 - zext_ln73_41_fu_1507_p1);

assign mult_33_fu_1473_p3 = {{data_24_val_read_reg_2580}, {3'd0}};

assign mult_34_fu_1532_p2 = (p_shl6_fu_1525_p3 - zext_ln73_39_fu_1480_p1);

assign mult_35_fu_1559_p2 = (9'd0 - zext_ln73_43_fu_1555_p1);

assign mult_36_fu_274_p0 = mult_36_fu_274_p00;

assign mult_36_fu_274_p00 = data_27_val;

assign mult_36_fu_274_p1 = 15'd32692;

assign mult_37_fu_1584_p2 = (zext_ln73_45_fu_1580_p1 - zext_ln73_44_fu_1576_p1);

assign mult_38_fu_1601_p2 = (10'd0 - zext_ln73_46_fu_1597_p1);

assign mult_39_fu_1622_p2 = (p_shl7_fu_1611_p3 - zext_ln73_47_fu_1618_p1);

assign mult_3_fu_943_p2 = (zext_ln73_4_fu_939_p1 - zext_ln73_3_fu_928_p1);

assign mult_40_fu_1636_p2 = (zext_ln73_48_fu_1632_p1 + zext_ln73_27_fu_1542_p1);

assign mult_41_fu_1650_p2 = (zext_ln73_49_fu_1646_p1 - zext_ln73_44_fu_1576_p1);

assign mult_42_fu_1677_p2 = (p_shl8_fu_1659_p3 - zext_ln73_50_fu_1673_p1);

assign mult_43_fu_1698_p2 = (12'd0 - zext_ln73_51_fu_1694_p1);

assign mult_44_fu_1666_p3 = {{data_29_val_read_reg_2561}, {3'd0}};

assign mult_4_fu_949_p2 = (zext_ln73_3_fu_928_p1 + zext_ln73_4_fu_939_p1);

assign mult_5_fu_281_p0 = mult_5_fu_281_p00;

assign mult_5_fu_281_p00 = data_6_val;

assign mult_5_fu_281_p1 = 13'd26;

assign mult_6_fu_980_p2 = (13'd0 - zext_ln73_8_fu_976_p1);

assign mult_7_fu_990_p3 = {{data_6_val_read_reg_2627}, {2'd0}};

assign mult_8_fu_1023_p2 = (zext_ln73_9_fu_1008_p1 + zext_ln73_10_fu_1019_p1);

assign mult_9_fu_1033_p2 = (12'd0 - zext_ln73_9_fu_1008_p1);

assign mult_fu_886_p2 = (p_shl1_fu_868_p3 - zext_ln73_1_fu_882_p1);

assign or_ln_fu_2385_p5 = {{{{tmp_s_fu_2367_p4}, {1'd1}}, {tmp_85_fu_2377_p3}}, {6'd32}};

assign p_shl18_fu_2167_p1 = tmp_83_fu_2159_p3;

assign p_shl19_fu_2067_p1 = tmp_81_fu_2059_p3;

assign p_shl1_fu_868_p3 = {{data_3_val_read_reg_2637}, {3'd0}};

assign p_shl20_fu_2079_p1 = tmp_82_fu_2071_p3;

assign p_shl21_fu_1969_p1 = tmp_79_fu_1961_p3;

assign p_shl23_fu_1981_p1 = tmp_80_fu_1973_p3;

assign p_shl24_fu_1799_p1 = tmp_78_fu_1791_p3;

assign p_shl2_fu_1043_p3 = {{data_10_val_read_reg_2618}, {6'd0}};

assign p_shl3_fu_1155_p3 = {{data_12_val_read_reg_2609}, {5'd0}};

assign p_shl4_fu_1349_p3 = {{data_22_val_read_reg_2590}, {7'd0}};

assign p_shl5_fu_1445_p3 = {{data_24_val_read_reg_2580}, {4'd0}};

assign p_shl6_fu_1525_p3 = {{data_24_val_read_reg_2580}, {5'd0}};

assign p_shl7_fu_1611_p3 = {{data_27_val_read_reg_2570}, {4'd0}};

assign p_shl8_fu_1659_p3 = {{data_29_val_read_reg_2561}, {5'd0}};

assign p_shl_fu_2317_p1 = tmp_84_fu_2309_p3;

assign sext_ln111_1_fu_2447_p1 = $signed(trunc_ln111_2_fu_2437_p4);

assign sext_ln111_2_fu_2461_p1 = $signed(trunc_ln111_3_fu_2451_p4);

assign sext_ln111_3_fu_2485_p1 = $signed(trunc_ln111_5_fu_2475_p4);

assign sext_ln111_4_fu_2499_p1 = $signed(trunc_ln111_6_fu_2489_p4);

assign sext_ln111_fu_2433_p1 = $signed(trunc_ln111_1_fu_2423_p4);

assign sext_ln17_10_fu_1565_p1 = $signed(mult_35_fu_1559_p2);

assign sext_ln17_11_fu_1607_p1 = $signed(mult_38_fu_1601_p2);

assign sext_ln17_12_fu_1704_p1 = $signed(mult_43_fu_1698_p2);

assign sext_ln17_1_fu_986_p1 = $signed(mult_6_fu_980_p2);

assign sext_ln17_2_fu_1039_p1 = $signed(mult_9_fu_1033_p2);

assign sext_ln17_3_fu_1088_p1 = $signed(mult_11_fu_1082_p2);

assign sext_ln17_4_fu_1120_p1 = $signed(mult_12_fu_1114_p2);

assign sext_ln17_5_fu_1134_p1 = $signed(mult_13_fu_1128_p2);

assign sext_ln17_6_fu_1148_p1 = $signed(mult_14_fu_1142_p2);

assign sext_ln17_7_fu_1234_p1 = $signed(mult_19_fu_1228_p2);

assign sext_ln17_8_fu_1281_p1 = $signed(mult_21_fu_1275_p2);

assign sext_ln17_9_fu_1334_p1 = $signed(mult_24_fu_1328_p2);

assign sext_ln17_fu_906_p1 = $signed(mult_1_fu_900_p2);

assign sext_ln58_10_fu_1945_p1 = $signed(add_ln58_18_fu_1939_p2);

assign sext_ln58_11_fu_1997_p1 = $signed(add_ln58_20_fu_1991_p2);

assign sext_ln58_12_fu_2007_p1 = $signed(add_ln58_21_fu_2001_p2);

assign sext_ln58_13_fu_2039_p1 = $signed(add_ln58_25_fu_2033_p2);

assign sext_ln58_14_fu_2049_p1 = $signed(add_ln58_26_fu_2043_p2);

assign sext_ln58_15_fu_2111_p1 = $signed(add_ln58_30_fu_2105_p2);

assign sext_ln58_16_fu_2143_p1 = $signed(add_ln58_34_fu_2137_p2);

assign sext_ln58_17_fu_2193_p1 = $signed(add_ln58_38_fu_2187_p2);

assign sext_ln58_18_fu_2209_p1 = $signed(sub_ln58_4_fu_2203_p2);

assign sext_ln58_19_fu_2231_p1 = $signed(add_ln58_41_fu_2225_p2);

assign sext_ln58_1_fu_1781_p1 = $signed(add_ln58_4_fu_1775_p2);

assign sext_ln58_20_fu_2241_p1 = $signed(add_ln58_42_fu_2235_p2);

assign sext_ln58_21_fu_2273_p1 = $signed(add_ln58_46_fu_2267_p2);

assign sext_ln58_22_fu_2283_p1 = $signed(add_ln58_47_fu_2277_p2);

assign sext_ln58_23_fu_2293_p1 = $signed(add_ln58_48_fu_2287_p2);

assign sext_ln58_24_fu_2333_p1 = $signed(sub_ln58_5_fu_2327_p2);

assign sext_ln58_25_fu_2343_p1 = $signed(add_ln58_50_fu_2337_p2);

assign sext_ln58_26_fu_2353_p1 = $signed(add_ln58_51_fu_2347_p2);

assign sext_ln58_27_fu_2363_p1 = $signed(add_ln58_52_fu_2357_p2);

assign sext_ln58_28_fu_2397_p1 = $signed(or_ln_fu_2385_p5);

assign sext_ln58_2_fu_1809_p1 = $signed(tmp3_fu_1803_p2);

assign sext_ln58_3_fu_1835_p1 = $signed(add_ln58_7_fu_1829_p2);

assign sext_ln58_4_fu_1857_p1 = $signed(add_ln58_9_fu_1851_p2);

assign sext_ln58_5_fu_1879_p1 = $signed(add_ln58_12_fu_1873_p2);

assign sext_ln58_6_fu_1889_p1 = $signed(add_ln58_13_fu_1883_p2);

assign sext_ln58_7_fu_1905_p1 = $signed(add_ln58_15_fu_1899_p2);

assign sext_ln58_8_fu_1925_p1 = $signed(sub_ln58_2_fu_1919_p2);

assign sext_ln58_9_fu_1935_p1 = $signed(add_ln58_17_fu_1929_p2);

assign sext_ln58_fu_1749_p1 = $signed(add_ln58_fu_1743_p2);

assign sub_ln17_fu_1719_p2 = (zext_ln17_21_fu_1715_p1 - tmp_76_fu_1687_p3);

assign sub_ln58_1_fu_1839_p2 = ($signed(sext_ln58_2_fu_1809_p1) - $signed(zext_ln73_37_fu_1441_p1));

assign sub_ln58_2_fu_1919_p2 = (12'd96 - zext_ln73_51_fu_1694_p1);

assign sub_ln58_3_fu_2197_p2 = (zext_ln17_18_fu_1628_p1 - zext_ln73_37_fu_1441_p1);

assign sub_ln58_4_fu_2203_p2 = ($signed(18'd261856) - $signed(p_shl18_fu_2167_p1));

assign sub_ln58_5_fu_2327_p2 = (zext_ln73_16_fu_1124_p1 - zext_ln17_1_fu_917_p1);

assign sub_ln58_fu_1823_p2 = (zext_ln17_6_fu_1067_p1 - zext_ln73_30_fu_1345_p1);

assign sub_ln73_10_fu_1484_p2 = (14'd0 - zext_ln73_39_fu_1480_p1);

assign sub_ln73_3_fu_1249_p2 = (13'd0 - zext_ln73_25_fu_1245_p1);

assign sub_ln73_fu_1187_p2 = (14'd0 - zext_ln73_20_fu_1183_p1);

assign tmp10_fu_2303_p2 = (zext_ln73_32_fu_1545_p1 + zext_ln73_5_fu_959_p1);

assign tmp11_fu_2321_p2 = (18'd0 - p_shl_fu_2317_p1);

assign tmp1_fu_1731_p3 = {{tmp_fu_1725_p2}, {2'd0}};

assign tmp3_fu_1803_p2 = (17'd0 - p_shl24_fu_1799_p1);

assign tmp4_fu_1955_p2 = (zext_ln73_6_fu_962_p1 + zext_ln73_fu_865_p1);

assign tmp5_fu_1985_p2 = (p_shl23_fu_1981_p1 - p_shl21_fu_1969_p1);

assign tmp7_fu_2083_p2 = (p_shl20_fu_2079_p1 - p_shl19_fu_2067_p1);

assign tmp8_fu_2153_p2 = (zext_ln73_33_fu_1656_p1 + zext_ln73_19_fu_1261_p1);

assign tmp_48_fu_875_p3 = {{data_3_val_read_reg_2637}, {1'd0}};

assign tmp_49_fu_921_p3 = {{data_3_val_read_reg_2637}, {5'd0}};

assign tmp_50_fu_932_p3 = {{data_3_val_read_reg_2637}, {2'd0}};

assign tmp_51_fu_969_p3 = {{data_6_val_read_reg_2627}, {4'd0}};

assign tmp_52_fu_1001_p3 = {{data_6_val_read_reg_2627}, {3'd0}};

assign tmp_53_fu_1012_p3 = {{data_6_val_read_reg_2627}, {1'd0}};

assign tmp_55_fu_1071_p3 = {{data_10_val_read_reg_2618}, {5'd0}};

assign tmp_56_fu_1092_p3 = {{data_10_val_read_reg_2618}, {3'd0}};

assign tmp_57_fu_1103_p3 = {{data_10_val_read_reg_2618}, {1'd0}};

assign tmp_58_fu_1162_p3 = {{data_12_val_read_reg_2609}, {2'd0}};

assign tmp_59_fu_1193_p3 = {{data_12_val_read_reg_2609}, {3'd0}};

assign tmp_60_fu_1238_p3 = {{data_12_val_read_reg_2609}, {4'd0}};

assign tmp_61_fu_1264_p3 = {{data_21_val_read_reg_2600}, {3'd0}};

assign tmp_62_fu_1296_p3 = {{data_21_val_read_reg_2600}, {1'd0}};

assign tmp_63_fu_1317_p3 = {{data_21_val_read_reg_2600}, {2'd0}};

assign tmp_64_fu_1338_p3 = {{data_22_val_read_reg_2590}, {9'd0}};

assign tmp_65_fu_1356_p3 = {{data_22_val_read_reg_2590}, {5'd0}};

assign tmp_66_fu_1388_p3 = {{data_22_val_read_reg_2590}, {6'd0}};

assign tmp_68_fu_1434_p3 = {{data_24_val_read_reg_2580}, {9'd0}};

assign tmp_69_fu_1452_p3 = {{data_24_val_read_reg_2580}, {1'd0}};

assign tmp_71_fu_1500_p3 = {{data_24_val_read_reg_2580}, {6'd0}};

assign tmp_72_fu_1548_p3 = {{data_27_val_read_reg_2570}, {1'd0}};

assign tmp_73_fu_1569_p3 = {{data_27_val_read_reg_2570}, {5'd0}};

assign tmp_74_fu_1590_p3 = {{data_27_val_read_reg_2570}, {2'd0}};

assign tmp_76_fu_1687_p3 = {{data_29_val_read_reg_2561}, {4'd0}};

assign tmp_77_fu_1708_p3 = {{data_29_val_read_reg_2561}, {2'd0}};

assign tmp_78_fu_1791_p3 = {{tmp_fu_1725_p2}, {7'd0}};

assign tmp_79_fu_1961_p3 = {{tmp4_fu_1955_p2}, {4'd0}};

assign tmp_80_fu_1973_p3 = {{tmp4_fu_1955_p2}, {2'd0}};

assign tmp_81_fu_2059_p3 = {{tmp4_fu_1955_p2}, {5'd0}};

assign tmp_82_fu_2071_p3 = {{tmp4_fu_1955_p2}, {3'd0}};

assign tmp_83_fu_2159_p3 = {{tmp8_fu_2153_p2}, {8'd0}};

assign tmp_84_fu_2309_p3 = {{tmp10_fu_2303_p2}, {8'd0}};

assign tmp_85_fu_2377_p3 = tmp11_fu_2321_p2[32'd6];

assign tmp_fu_1725_p2 = (zext_ln73_19_fu_1261_p1 + zext_ln73_14_fu_1152_p1);

assign tmp_s_fu_2367_p4 = {{tmp11_fu_2321_p2[17:8]}};

assign trunc_ln111_1_fu_2423_p4 = {{add_ln58_19_fu_1949_p2[16:6]}};

assign trunc_ln111_2_fu_2437_p4 = {{add_ln58_27_fu_2053_p2[15:6]}};

assign trunc_ln111_3_fu_2451_p4 = {{add_ln58_35_fu_2147_p2[16:6]}};

assign trunc_ln111_5_fu_2475_p4 = {{add_ln58_49_fu_2297_p2[16:6]}};

assign trunc_ln111_6_fu_2489_p4 = {{add_ln58_5_fu_1785_p2[15:6]}};

assign zext_ln17_10_fu_1373_p1 = mult_25_fu_1367_p2;

assign zext_ln17_11_fu_1384_p1 = mult_26_fu_1377_p3;

assign zext_ln17_12_fu_1416_p1 = mult_27_fu_1410_p2;

assign zext_ln17_13_fu_1420_p1 = mult_28_fu_1399_p3;

assign zext_ln17_14_fu_1424_p1 = mult_28_fu_1399_p3;

assign zext_ln17_15_fu_1469_p1 = mult_30_fu_1463_p2;

assign zext_ln17_16_fu_1521_p1 = mult_33_fu_1473_p3;

assign zext_ln17_17_fu_1538_p1 = mult_34_fu_1532_p2;

assign zext_ln17_18_fu_1628_p1 = mult_39_fu_1622_p2;

assign zext_ln17_19_fu_1642_p1 = mult_40_fu_1636_p2;

assign zext_ln17_1_fu_917_p1 = mult_2_fu_910_p3;

assign zext_ln17_20_fu_1683_p1 = mult_42_fu_1677_p2;

assign zext_ln17_21_fu_1715_p1 = tmp_77_fu_1708_p3;

assign zext_ln17_2_fu_955_p1 = mult_4_fu_949_p2;

assign zext_ln17_3_fu_965_p1 = mult_5_reg_846;

assign zext_ln17_4_fu_997_p1 = mult_7_fu_990_p3;

assign zext_ln17_5_fu_1029_p1 = mult_8_fu_1023_p2;

assign zext_ln17_6_fu_1067_p1 = mult_10_fu_1061_p2;

assign zext_ln17_7_fu_1179_p1 = mult_16_fu_1173_p2;

assign zext_ln17_8_fu_1292_p1 = mult_22_fu_1285_p3;

assign zext_ln17_9_fu_1313_p1 = mult_23_fu_1307_p2;

assign zext_ln17_fu_892_p1 = mult_fu_886_p2;

assign zext_ln58_1_fu_1765_p1 = add_ln58_2_fu_1759_p2;

assign zext_ln58_2_fu_1819_p1 = add_ln58_6_fu_1813_p2;

assign zext_ln58_3_fu_1915_p1 = add_ln58_16_fu_1909_p2;

assign zext_ln58_4_fu_2029_p1 = add_ln58_24_fu_2023_p2;

assign zext_ln58_5_fu_2101_p1 = add_ln58_29_fu_2095_p2;

assign zext_ln58_6_fu_2133_p1 = add_ln58_33_fu_2127_p2;

assign zext_ln58_7_fu_2177_p1 = add_ln58_36_fu_2171_p2;

assign zext_ln58_8_fu_2263_p1 = add_ln58_45_fu_2257_p2;

assign zext_ln58_fu_1739_p1 = tmp1_fu_1731_p3;

assign zext_ln73_10_fu_1019_p1 = tmp_53_fu_1012_p3;

assign zext_ln73_11_fu_1057_p1 = mult_15_fu_1050_p3;

assign zext_ln73_12_fu_1078_p1 = tmp_55_fu_1071_p3;

assign zext_ln73_13_fu_1099_p1 = tmp_56_fu_1092_p3;

assign zext_ln73_14_fu_1152_p1 = data_12_val_read_reg_2609;

assign zext_ln73_15_fu_1110_p1 = tmp_57_fu_1103_p3;

assign zext_ln73_16_fu_1124_p1 = mult_15_fu_1050_p3;

assign zext_ln73_17_fu_1138_p1 = p_shl2_fu_1043_p3;

assign zext_ln73_18_fu_1169_p1 = tmp_58_fu_1162_p3;

assign zext_ln73_19_fu_1261_p1 = data_21_val_read_reg_2600;

assign zext_ln73_1_fu_882_p1 = tmp_48_fu_875_p3;

assign zext_ln73_20_fu_1183_p1 = p_shl3_fu_1155_p3;

assign zext_ln73_21_fu_1200_p1 = tmp_59_fu_1193_p3;

assign zext_ln73_22_fu_1210_p1 = p_shl3_fu_1155_p3;

assign zext_ln73_23_fu_1214_p1 = tmp_58_fu_1162_p3;

assign zext_ln73_24_fu_1224_p1 = tmp_59_fu_1193_p3;

assign zext_ln73_25_fu_1245_p1 = tmp_60_fu_1238_p3;

assign zext_ln73_26_fu_1271_p1 = tmp_61_fu_1264_p3;

assign zext_ln73_27_fu_1542_p1 = data_27_val_read_reg_2570;

assign zext_ln73_28_fu_1303_p1 = tmp_62_fu_1296_p3;

assign zext_ln73_29_fu_1324_p1 = tmp_63_fu_1317_p3;

assign zext_ln73_2_fu_896_p1 = tmp_48_fu_875_p3;

assign zext_ln73_30_fu_1345_p1 = tmp_64_fu_1338_p3;

assign zext_ln73_32_fu_1545_p1 = data_27_val_read_reg_2570;

assign zext_ln73_33_fu_1656_p1 = data_29_val_read_reg_2561;

assign zext_ln73_34_fu_1363_p1 = tmp_65_fu_1356_p3;

assign zext_ln73_35_fu_1395_p1 = tmp_66_fu_1388_p3;

assign zext_ln73_36_fu_1406_p1 = mult_28_fu_1399_p3;

assign zext_ln73_37_fu_1441_p1 = tmp_68_fu_1434_p3;

assign zext_ln73_38_fu_1459_p1 = tmp_69_fu_1452_p3;

assign zext_ln73_39_fu_1480_p1 = mult_33_fu_1473_p3;

assign zext_ln73_3_fu_928_p1 = tmp_49_fu_921_p3;

assign zext_ln73_40_fu_1490_p1 = tmp_69_fu_1452_p3;

assign zext_ln73_41_fu_1507_p1 = tmp_71_fu_1500_p3;

assign zext_ln73_42_fu_1511_p1 = p_shl5_fu_1445_p3;

assign zext_ln73_43_fu_1555_p1 = tmp_72_fu_1548_p3;

assign zext_ln73_44_fu_1576_p1 = tmp_73_fu_1569_p3;

assign zext_ln73_45_fu_1580_p1 = tmp_72_fu_1548_p3;

assign zext_ln73_46_fu_1597_p1 = tmp_74_fu_1590_p3;

assign zext_ln73_47_fu_1618_p1 = tmp_74_fu_1590_p3;

assign zext_ln73_48_fu_1632_p1 = p_shl7_fu_1611_p3;

assign zext_ln73_49_fu_1646_p1 = tmp_74_fu_1590_p3;

assign zext_ln73_4_fu_939_p1 = tmp_50_fu_932_p3;

assign zext_ln73_50_fu_1673_p1 = mult_44_fu_1666_p3;

assign zext_ln73_51_fu_1694_p1 = tmp_76_fu_1687_p3;

assign zext_ln73_5_fu_959_p1 = data_6_val_read_reg_2627;

assign zext_ln73_6_fu_962_p1 = data_6_val_read_reg_2627;

assign zext_ln73_8_fu_976_p1 = tmp_51_fu_969_p3;

assign zext_ln73_9_fu_1008_p1 = tmp_52_fu_1001_p3;

assign zext_ln73_fu_865_p1 = data_3_val_read_reg_2637;

endmodule //myproject_dense_latency_ap_ufixed_9_7_5_3_0_ap_fixed_13_11_5_3_0_config13_s
