// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_13_10_5_3_0_ap_ufixed_9_6_5_3_0_ReLU_config11_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_3_val,
        data_4_val,
        data_6_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_19_val,
        data_20_val,
        data_22_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_rst
);


output   ap_ready;
input  [12:0] data_0_val;
input  [12:0] data_1_val;
input  [12:0] data_3_val;
input  [12:0] data_4_val;
input  [12:0] data_6_val;
input  [12:0] data_8_val;
input  [12:0] data_9_val;
input  [12:0] data_10_val;
input  [12:0] data_11_val;
input  [12:0] data_12_val;
input  [12:0] data_14_val;
input  [12:0] data_15_val;
input  [12:0] data_16_val;
input  [12:0] data_17_val;
input  [12:0] data_19_val;
input  [12:0] data_20_val;
input  [12:0] data_22_val;
input  [12:0] data_24_val;
input  [12:0] data_25_val;
input  [12:0] data_26_val;
input  [12:0] data_27_val;
input  [12:0] data_28_val;
input  [12:0] data_31_val;
output  [8:0] ap_return_0;
output  [8:0] ap_return_1;
output  [8:0] ap_return_2;
output  [8:0] ap_return_3;
output  [8:0] ap_return_4;
output  [8:0] ap_return_5;
output  [8:0] ap_return_6;
output  [8:0] ap_return_7;
output  [8:0] ap_return_8;
output  [8:0] ap_return_9;
output  [8:0] ap_return_10;
output  [8:0] ap_return_11;
output  [8:0] ap_return_12;
output  [8:0] ap_return_13;
output  [8:0] ap_return_14;
output  [8:0] ap_return_15;
output  [8:0] ap_return_16;
output  [8:0] ap_return_17;
output  [8:0] ap_return_18;
output  [8:0] ap_return_19;
output  [8:0] ap_return_20;
output  [8:0] ap_return_21;
output  [8:0] ap_return_22;
input   ap_rst;

wire   [0:0] icmp_ln45_fu_200_p2;
wire   [8:0] trunc_ln46_fu_206_p1;
wire   [0:0] icmp_ln45_74_fu_218_p2;
wire   [8:0] trunc_ln46_74_fu_224_p1;
wire   [0:0] icmp_ln45_75_fu_236_p2;
wire   [8:0] trunc_ln46_75_fu_242_p1;
wire   [0:0] icmp_ln45_76_fu_254_p2;
wire   [8:0] trunc_ln46_76_fu_260_p1;
wire   [0:0] icmp_ln45_77_fu_272_p2;
wire   [8:0] trunc_ln46_77_fu_278_p1;
wire   [0:0] icmp_ln45_78_fu_290_p2;
wire   [8:0] trunc_ln46_78_fu_296_p1;
wire   [0:0] icmp_ln45_79_fu_308_p2;
wire   [8:0] trunc_ln46_79_fu_314_p1;
wire   [0:0] icmp_ln45_80_fu_326_p2;
wire   [8:0] trunc_ln46_80_fu_332_p1;
wire   [0:0] icmp_ln45_81_fu_344_p2;
wire   [8:0] trunc_ln46_81_fu_350_p1;
wire   [0:0] icmp_ln45_82_fu_362_p2;
wire   [8:0] trunc_ln46_82_fu_368_p1;
wire   [0:0] icmp_ln45_83_fu_380_p2;
wire   [8:0] trunc_ln46_83_fu_386_p1;
wire   [0:0] icmp_ln45_84_fu_398_p2;
wire   [8:0] trunc_ln46_84_fu_404_p1;
wire   [0:0] icmp_ln45_85_fu_416_p2;
wire   [8:0] trunc_ln46_85_fu_422_p1;
wire   [0:0] icmp_ln45_86_fu_434_p2;
wire   [8:0] trunc_ln46_86_fu_440_p1;
wire   [0:0] icmp_ln45_87_fu_452_p2;
wire   [8:0] trunc_ln46_87_fu_458_p1;
wire   [0:0] icmp_ln45_88_fu_470_p2;
wire   [8:0] trunc_ln46_88_fu_476_p1;
wire   [0:0] icmp_ln45_89_fu_488_p2;
wire   [8:0] trunc_ln46_89_fu_494_p1;
wire   [0:0] icmp_ln45_90_fu_506_p2;
wire   [8:0] trunc_ln46_90_fu_512_p1;
wire   [0:0] icmp_ln45_91_fu_524_p2;
wire   [8:0] trunc_ln46_91_fu_530_p1;
wire   [0:0] icmp_ln45_92_fu_542_p2;
wire   [8:0] trunc_ln46_92_fu_548_p1;
wire   [0:0] icmp_ln45_93_fu_560_p2;
wire   [8:0] trunc_ln46_93_fu_566_p1;
wire   [0:0] icmp_ln45_94_fu_578_p2;
wire   [8:0] trunc_ln46_94_fu_584_p1;
wire   [0:0] icmp_ln45_95_fu_596_p2;
wire   [8:0] trunc_ln46_95_fu_602_p1;
wire   [8:0] select_ln45_fu_210_p3;
wire   [8:0] select_ln45_74_fu_228_p3;
wire   [8:0] select_ln45_75_fu_246_p3;
wire   [8:0] select_ln45_76_fu_264_p3;
wire   [8:0] select_ln45_77_fu_282_p3;
wire   [8:0] select_ln45_78_fu_300_p3;
wire   [8:0] select_ln45_79_fu_318_p3;
wire   [8:0] select_ln45_80_fu_336_p3;
wire   [8:0] select_ln45_81_fu_354_p3;
wire   [8:0] select_ln45_82_fu_372_p3;
wire   [8:0] select_ln45_83_fu_390_p3;
wire   [8:0] select_ln45_84_fu_408_p3;
wire   [8:0] select_ln45_85_fu_426_p3;
wire   [8:0] select_ln45_86_fu_444_p3;
wire   [8:0] select_ln45_87_fu_462_p3;
wire   [8:0] select_ln45_88_fu_480_p3;
wire   [8:0] select_ln45_89_fu_498_p3;
wire   [8:0] select_ln45_90_fu_516_p3;
wire   [8:0] select_ln45_91_fu_534_p3;
wire   [8:0] select_ln45_92_fu_552_p3;
wire   [8:0] select_ln45_93_fu_570_p3;
wire   [8:0] select_ln45_94_fu_588_p3;
wire   [8:0] select_ln45_95_fu_606_p3;

assign ap_ready = 1'b1;

assign select_ln45_74_fu_228_p3 = ((icmp_ln45_74_fu_218_p2[0:0] == 1'b1) ? trunc_ln46_74_fu_224_p1 : 9'd0);

assign select_ln45_75_fu_246_p3 = ((icmp_ln45_75_fu_236_p2[0:0] == 1'b1) ? trunc_ln46_75_fu_242_p1 : 9'd0);

assign select_ln45_76_fu_264_p3 = ((icmp_ln45_76_fu_254_p2[0:0] == 1'b1) ? trunc_ln46_76_fu_260_p1 : 9'd0);

assign select_ln45_77_fu_282_p3 = ((icmp_ln45_77_fu_272_p2[0:0] == 1'b1) ? trunc_ln46_77_fu_278_p1 : 9'd0);

assign select_ln45_78_fu_300_p3 = ((icmp_ln45_78_fu_290_p2[0:0] == 1'b1) ? trunc_ln46_78_fu_296_p1 : 9'd0);

assign select_ln45_79_fu_318_p3 = ((icmp_ln45_79_fu_308_p2[0:0] == 1'b1) ? trunc_ln46_79_fu_314_p1 : 9'd0);

assign select_ln45_80_fu_336_p3 = ((icmp_ln45_80_fu_326_p2[0:0] == 1'b1) ? trunc_ln46_80_fu_332_p1 : 9'd0);

assign select_ln45_81_fu_354_p3 = ((icmp_ln45_81_fu_344_p2[0:0] == 1'b1) ? trunc_ln46_81_fu_350_p1 : 9'd0);

assign select_ln45_82_fu_372_p3 = ((icmp_ln45_82_fu_362_p2[0:0] == 1'b1) ? trunc_ln46_82_fu_368_p1 : 9'd0);

assign select_ln45_83_fu_390_p3 = ((icmp_ln45_83_fu_380_p2[0:0] == 1'b1) ? trunc_ln46_83_fu_386_p1 : 9'd0);

assign select_ln45_84_fu_408_p3 = ((icmp_ln45_84_fu_398_p2[0:0] == 1'b1) ? trunc_ln46_84_fu_404_p1 : 9'd0);

assign select_ln45_85_fu_426_p3 = ((icmp_ln45_85_fu_416_p2[0:0] == 1'b1) ? trunc_ln46_85_fu_422_p1 : 9'd0);

assign select_ln45_86_fu_444_p3 = ((icmp_ln45_86_fu_434_p2[0:0] == 1'b1) ? trunc_ln46_86_fu_440_p1 : 9'd0);

assign select_ln45_87_fu_462_p3 = ((icmp_ln45_87_fu_452_p2[0:0] == 1'b1) ? trunc_ln46_87_fu_458_p1 : 9'd0);

assign select_ln45_88_fu_480_p3 = ((icmp_ln45_88_fu_470_p2[0:0] == 1'b1) ? trunc_ln46_88_fu_476_p1 : 9'd0);

assign select_ln45_89_fu_498_p3 = ((icmp_ln45_89_fu_488_p2[0:0] == 1'b1) ? trunc_ln46_89_fu_494_p1 : 9'd0);

assign select_ln45_90_fu_516_p3 = ((icmp_ln45_90_fu_506_p2[0:0] == 1'b1) ? trunc_ln46_90_fu_512_p1 : 9'd0);

assign select_ln45_91_fu_534_p3 = ((icmp_ln45_91_fu_524_p2[0:0] == 1'b1) ? trunc_ln46_91_fu_530_p1 : 9'd0);

assign select_ln45_92_fu_552_p3 = ((icmp_ln45_92_fu_542_p2[0:0] == 1'b1) ? trunc_ln46_92_fu_548_p1 : 9'd0);

assign select_ln45_93_fu_570_p3 = ((icmp_ln45_93_fu_560_p2[0:0] == 1'b1) ? trunc_ln46_93_fu_566_p1 : 9'd0);

assign select_ln45_94_fu_588_p3 = ((icmp_ln45_94_fu_578_p2[0:0] == 1'b1) ? trunc_ln46_94_fu_584_p1 : 9'd0);

assign select_ln45_95_fu_606_p3 = ((icmp_ln45_95_fu_596_p2[0:0] == 1'b1) ? trunc_ln46_95_fu_602_p1 : 9'd0);

assign select_ln45_fu_210_p3 = ((icmp_ln45_fu_200_p2[0:0] == 1'b1) ? trunc_ln46_fu_206_p1 : 9'd0);

assign trunc_ln46_74_fu_224_p1 = data_1_val[8:0];

assign trunc_ln46_75_fu_242_p1 = data_3_val[8:0];

assign trunc_ln46_76_fu_260_p1 = data_4_val[8:0];

assign trunc_ln46_77_fu_278_p1 = data_6_val[8:0];

assign trunc_ln46_78_fu_296_p1 = data_8_val[8:0];

assign trunc_ln46_79_fu_314_p1 = data_9_val[8:0];

assign trunc_ln46_80_fu_332_p1 = data_10_val[8:0];

assign trunc_ln46_81_fu_350_p1 = data_11_val[8:0];

assign trunc_ln46_82_fu_368_p1 = data_12_val[8:0];

assign trunc_ln46_83_fu_386_p1 = data_14_val[8:0];

assign trunc_ln46_84_fu_404_p1 = data_15_val[8:0];

assign trunc_ln46_85_fu_422_p1 = data_16_val[8:0];

assign trunc_ln46_86_fu_440_p1 = data_17_val[8:0];

assign trunc_ln46_87_fu_458_p1 = data_19_val[8:0];

assign trunc_ln46_88_fu_476_p1 = data_20_val[8:0];

assign trunc_ln46_89_fu_494_p1 = data_22_val[8:0];

assign trunc_ln46_90_fu_512_p1 = data_24_val[8:0];

assign trunc_ln46_91_fu_530_p1 = data_25_val[8:0];

assign trunc_ln46_92_fu_548_p1 = data_26_val[8:0];

assign trunc_ln46_93_fu_566_p1 = data_27_val[8:0];

assign trunc_ln46_94_fu_584_p1 = data_28_val[8:0];

assign trunc_ln46_95_fu_602_p1 = data_31_val[8:0];

assign trunc_ln46_fu_206_p1 = data_0_val[8:0];

assign ap_return_0 = select_ln45_fu_210_p3;

assign ap_return_1 = select_ln45_74_fu_228_p3;

assign ap_return_10 = select_ln45_83_fu_390_p3;

assign ap_return_11 = select_ln45_84_fu_408_p3;

assign ap_return_12 = select_ln45_85_fu_426_p3;

assign ap_return_13 = select_ln45_86_fu_444_p3;

assign ap_return_14 = select_ln45_87_fu_462_p3;

assign ap_return_15 = select_ln45_88_fu_480_p3;

assign ap_return_16 = select_ln45_89_fu_498_p3;

assign ap_return_17 = select_ln45_90_fu_516_p3;

assign ap_return_18 = select_ln45_91_fu_534_p3;

assign ap_return_19 = select_ln45_92_fu_552_p3;

assign ap_return_2 = select_ln45_75_fu_246_p3;

assign ap_return_20 = select_ln45_93_fu_570_p3;

assign ap_return_21 = select_ln45_94_fu_588_p3;

assign ap_return_22 = select_ln45_95_fu_606_p3;

assign ap_return_3 = select_ln45_76_fu_264_p3;

assign ap_return_4 = select_ln45_77_fu_282_p3;

assign ap_return_5 = select_ln45_78_fu_300_p3;

assign ap_return_6 = select_ln45_79_fu_318_p3;

assign ap_return_7 = select_ln45_80_fu_336_p3;

assign ap_return_8 = select_ln45_81_fu_354_p3;

assign ap_return_9 = select_ln45_82_fu_372_p3;

assign icmp_ln45_74_fu_218_p2 = (($signed(data_1_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_75_fu_236_p2 = (($signed(data_3_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_76_fu_254_p2 = (($signed(data_4_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_77_fu_272_p2 = (($signed(data_6_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_78_fu_290_p2 = (($signed(data_8_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_79_fu_308_p2 = (($signed(data_9_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_80_fu_326_p2 = (($signed(data_10_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_81_fu_344_p2 = (($signed(data_11_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_82_fu_362_p2 = (($signed(data_12_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_83_fu_380_p2 = (($signed(data_14_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_84_fu_398_p2 = (($signed(data_15_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_85_fu_416_p2 = (($signed(data_16_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_86_fu_434_p2 = (($signed(data_17_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_87_fu_452_p2 = (($signed(data_19_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_88_fu_470_p2 = (($signed(data_20_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_89_fu_488_p2 = (($signed(data_22_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_90_fu_506_p2 = (($signed(data_24_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_91_fu_524_p2 = (($signed(data_25_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_92_fu_542_p2 = (($signed(data_26_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_93_fu_560_p2 = (($signed(data_27_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_94_fu_578_p2 = (($signed(data_28_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_95_fu_596_p2 = (($signed(data_31_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_200_p2 = (($signed(data_0_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_13_10_5_3_0_ap_ufixed_9_6_5_3_0_ReLU_config11_s
