Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
InputData: null
KerasModel: !keras_model '/home/hep/lr1424/hls4ml-tutorial_OPENML/model_3.1_1/hls4ml_prj/keras_model.keras'
OutputDir: /home/hep/lr1424/hls4ml-tutorial_OPENML/model_3.1_1/hls4ml_prj
OutputPredictions: null
Part: xcu50-fsvh2104-2-e
ProjectName: myproject
Stamp: 9da2ba93
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
