-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_13_10_5_3_0_ap_ufixed_9_6_5_3_0_ReLU_config11_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_17_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_19_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_20_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_24_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_26_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_27_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_28_val : IN STD_LOGIC_VECTOR (12 downto 0);
    data_31_val : IN STD_LOGIC_VECTOR (12 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of myproject_relu_ap_fixed_13_10_5_3_0_ap_ufixed_9_6_5_3_0_ReLU_config11_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_fu_206_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_74_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_74_fu_224_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_75_fu_236_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_75_fu_242_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_76_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_76_fu_260_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_77_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_77_fu_278_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_78_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_78_fu_296_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_79_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_79_fu_314_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_80_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_80_fu_332_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_81_fu_344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_81_fu_350_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_82_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_82_fu_368_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_83_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_83_fu_386_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_84_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_84_fu_404_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_85_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_85_fu_422_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_86_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_86_fu_440_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_87_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_87_fu_458_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_88_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_88_fu_476_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_89_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_89_fu_494_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_90_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_90_fu_512_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_91_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_91_fu_530_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_92_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_92_fu_548_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_93_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_93_fu_566_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_94_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_94_fu_584_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln45_95_fu_596_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln46_95_fu_602_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_fu_210_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_74_fu_228_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_75_fu_246_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_76_fu_264_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_77_fu_282_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_78_fu_300_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_79_fu_318_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_80_fu_336_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_81_fu_354_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_82_fu_372_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_83_fu_390_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_84_fu_408_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_85_fu_426_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_86_fu_444_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_87_fu_462_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_88_fu_480_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_89_fu_498_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_90_fu_516_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_91_fu_534_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_92_fu_552_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_93_fu_570_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_94_fu_588_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln45_95_fu_606_p3 : STD_LOGIC_VECTOR (8 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln45_fu_210_p3;
    ap_return_1 <= select_ln45_74_fu_228_p3;
    ap_return_10 <= select_ln45_83_fu_390_p3;
    ap_return_11 <= select_ln45_84_fu_408_p3;
    ap_return_12 <= select_ln45_85_fu_426_p3;
    ap_return_13 <= select_ln45_86_fu_444_p3;
    ap_return_14 <= select_ln45_87_fu_462_p3;
    ap_return_15 <= select_ln45_88_fu_480_p3;
    ap_return_16 <= select_ln45_89_fu_498_p3;
    ap_return_17 <= select_ln45_90_fu_516_p3;
    ap_return_18 <= select_ln45_91_fu_534_p3;
    ap_return_19 <= select_ln45_92_fu_552_p3;
    ap_return_2 <= select_ln45_75_fu_246_p3;
    ap_return_20 <= select_ln45_93_fu_570_p3;
    ap_return_21 <= select_ln45_94_fu_588_p3;
    ap_return_22 <= select_ln45_95_fu_606_p3;
    ap_return_3 <= select_ln45_76_fu_264_p3;
    ap_return_4 <= select_ln45_77_fu_282_p3;
    ap_return_5 <= select_ln45_78_fu_300_p3;
    ap_return_6 <= select_ln45_79_fu_318_p3;
    ap_return_7 <= select_ln45_80_fu_336_p3;
    ap_return_8 <= select_ln45_81_fu_354_p3;
    ap_return_9 <= select_ln45_82_fu_372_p3;
    icmp_ln45_74_fu_218_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_75_fu_236_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_76_fu_254_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_77_fu_272_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_78_fu_290_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_79_fu_308_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_80_fu_326_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_81_fu_344_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_82_fu_362_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_83_fu_380_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_84_fu_398_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_85_fu_416_p2 <= "1" when (signed(data_16_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_86_fu_434_p2 <= "1" when (signed(data_17_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_87_fu_452_p2 <= "1" when (signed(data_19_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_88_fu_470_p2 <= "1" when (signed(data_20_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_89_fu_488_p2 <= "1" when (signed(data_22_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_90_fu_506_p2 <= "1" when (signed(data_24_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_91_fu_524_p2 <= "1" when (signed(data_25_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_92_fu_542_p2 <= "1" when (signed(data_26_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_93_fu_560_p2 <= "1" when (signed(data_27_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_94_fu_578_p2 <= "1" when (signed(data_28_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_95_fu_596_p2 <= "1" when (signed(data_31_val) > signed(ap_const_lv13_0)) else "0";
    icmp_ln45_fu_200_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv13_0)) else "0";
    select_ln45_74_fu_228_p3 <= 
        trunc_ln46_74_fu_224_p1 when (icmp_ln45_74_fu_218_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_75_fu_246_p3 <= 
        trunc_ln46_75_fu_242_p1 when (icmp_ln45_75_fu_236_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_76_fu_264_p3 <= 
        trunc_ln46_76_fu_260_p1 when (icmp_ln45_76_fu_254_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_77_fu_282_p3 <= 
        trunc_ln46_77_fu_278_p1 when (icmp_ln45_77_fu_272_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_78_fu_300_p3 <= 
        trunc_ln46_78_fu_296_p1 when (icmp_ln45_78_fu_290_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_79_fu_318_p3 <= 
        trunc_ln46_79_fu_314_p1 when (icmp_ln45_79_fu_308_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_80_fu_336_p3 <= 
        trunc_ln46_80_fu_332_p1 when (icmp_ln45_80_fu_326_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_81_fu_354_p3 <= 
        trunc_ln46_81_fu_350_p1 when (icmp_ln45_81_fu_344_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_82_fu_372_p3 <= 
        trunc_ln46_82_fu_368_p1 when (icmp_ln45_82_fu_362_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_83_fu_390_p3 <= 
        trunc_ln46_83_fu_386_p1 when (icmp_ln45_83_fu_380_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_84_fu_408_p3 <= 
        trunc_ln46_84_fu_404_p1 when (icmp_ln45_84_fu_398_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_85_fu_426_p3 <= 
        trunc_ln46_85_fu_422_p1 when (icmp_ln45_85_fu_416_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_86_fu_444_p3 <= 
        trunc_ln46_86_fu_440_p1 when (icmp_ln45_86_fu_434_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_87_fu_462_p3 <= 
        trunc_ln46_87_fu_458_p1 when (icmp_ln45_87_fu_452_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_88_fu_480_p3 <= 
        trunc_ln46_88_fu_476_p1 when (icmp_ln45_88_fu_470_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_89_fu_498_p3 <= 
        trunc_ln46_89_fu_494_p1 when (icmp_ln45_89_fu_488_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_90_fu_516_p3 <= 
        trunc_ln46_90_fu_512_p1 when (icmp_ln45_90_fu_506_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_91_fu_534_p3 <= 
        trunc_ln46_91_fu_530_p1 when (icmp_ln45_91_fu_524_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_92_fu_552_p3 <= 
        trunc_ln46_92_fu_548_p1 when (icmp_ln45_92_fu_542_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_93_fu_570_p3 <= 
        trunc_ln46_93_fu_566_p1 when (icmp_ln45_93_fu_560_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_94_fu_588_p3 <= 
        trunc_ln46_94_fu_584_p1 when (icmp_ln45_94_fu_578_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_95_fu_606_p3 <= 
        trunc_ln46_95_fu_602_p1 when (icmp_ln45_95_fu_596_p2(0) = '1') else 
        ap_const_lv9_0;
    select_ln45_fu_210_p3 <= 
        trunc_ln46_fu_206_p1 when (icmp_ln45_fu_200_p2(0) = '1') else 
        ap_const_lv9_0;
    trunc_ln46_74_fu_224_p1 <= data_1_val(9 - 1 downto 0);
    trunc_ln46_75_fu_242_p1 <= data_3_val(9 - 1 downto 0);
    trunc_ln46_76_fu_260_p1 <= data_4_val(9 - 1 downto 0);
    trunc_ln46_77_fu_278_p1 <= data_6_val(9 - 1 downto 0);
    trunc_ln46_78_fu_296_p1 <= data_8_val(9 - 1 downto 0);
    trunc_ln46_79_fu_314_p1 <= data_9_val(9 - 1 downto 0);
    trunc_ln46_80_fu_332_p1 <= data_10_val(9 - 1 downto 0);
    trunc_ln46_81_fu_350_p1 <= data_11_val(9 - 1 downto 0);
    trunc_ln46_82_fu_368_p1 <= data_12_val(9 - 1 downto 0);
    trunc_ln46_83_fu_386_p1 <= data_14_val(9 - 1 downto 0);
    trunc_ln46_84_fu_404_p1 <= data_15_val(9 - 1 downto 0);
    trunc_ln46_85_fu_422_p1 <= data_16_val(9 - 1 downto 0);
    trunc_ln46_86_fu_440_p1 <= data_17_val(9 - 1 downto 0);
    trunc_ln46_87_fu_458_p1 <= data_19_val(9 - 1 downto 0);
    trunc_ln46_88_fu_476_p1 <= data_20_val(9 - 1 downto 0);
    trunc_ln46_89_fu_494_p1 <= data_22_val(9 - 1 downto 0);
    trunc_ln46_90_fu_512_p1 <= data_24_val(9 - 1 downto 0);
    trunc_ln46_91_fu_530_p1 <= data_25_val(9 - 1 downto 0);
    trunc_ln46_92_fu_548_p1 <= data_26_val(9 - 1 downto 0);
    trunc_ln46_93_fu_566_p1 <= data_27_val(9 - 1 downto 0);
    trunc_ln46_94_fu_584_p1 <= data_28_val(9 - 1 downto 0);
    trunc_ln46_95_fu_602_p1 <= data_31_val(9 - 1 downto 0);
    trunc_ln46_fu_206_p1 <= data_0_val(9 - 1 downto 0);
end behav;
