// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_ap_fixed_13_6_5_3_0_ap_ufixed_12_5_5_3_0_ReLU_config6_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        data_33_val,
        data_34_val,
        data_35_val,
        data_36_val,
        data_37_val,
        data_38_val,
        data_39_val,
        data_40_val,
        data_41_val,
        data_42_val,
        data_43_val,
        data_44_val,
        data_45_val,
        data_46_val,
        data_47_val,
        data_48_val,
        data_49_val,
        data_50_val,
        data_51_val,
        data_52_val,
        data_53_val,
        data_54_val,
        data_55_val,
        data_56_val,
        data_57_val,
        data_58_val,
        data_59_val,
        data_60_val,
        data_61_val,
        data_62_val,
        data_63_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59,
        ap_return_60,
        ap_return_61,
        ap_return_62,
        ap_rst
);


output   ap_ready;
input  [12:0] data_0_val;
input  [12:0] data_1_val;
input  [12:0] data_2_val;
input  [12:0] data_3_val;
input  [12:0] data_4_val;
input  [12:0] data_5_val;
input  [12:0] data_6_val;
input  [12:0] data_7_val;
input  [12:0] data_8_val;
input  [12:0] data_9_val;
input  [12:0] data_10_val;
input  [12:0] data_11_val;
input  [12:0] data_12_val;
input  [12:0] data_13_val;
input  [12:0] data_14_val;
input  [12:0] data_15_val;
input  [12:0] data_16_val;
input  [12:0] data_17_val;
input  [12:0] data_18_val;
input  [12:0] data_19_val;
input  [12:0] data_20_val;
input  [12:0] data_21_val;
input  [12:0] data_22_val;
input  [12:0] data_23_val;
input  [12:0] data_24_val;
input  [12:0] data_25_val;
input  [12:0] data_26_val;
input  [12:0] data_27_val;
input  [12:0] data_28_val;
input  [12:0] data_29_val;
input  [12:0] data_30_val;
input  [12:0] data_31_val;
input  [12:0] data_33_val;
input  [12:0] data_34_val;
input  [12:0] data_35_val;
input  [12:0] data_36_val;
input  [12:0] data_37_val;
input  [12:0] data_38_val;
input  [12:0] data_39_val;
input  [12:0] data_40_val;
input  [12:0] data_41_val;
input  [12:0] data_42_val;
input  [12:0] data_43_val;
input  [12:0] data_44_val;
input  [12:0] data_45_val;
input  [12:0] data_46_val;
input  [12:0] data_47_val;
input  [12:0] data_48_val;
input  [12:0] data_49_val;
input  [12:0] data_50_val;
input  [12:0] data_51_val;
input  [12:0] data_52_val;
input  [12:0] data_53_val;
input  [12:0] data_54_val;
input  [12:0] data_55_val;
input  [12:0] data_56_val;
input  [12:0] data_57_val;
input  [12:0] data_58_val;
input  [12:0] data_59_val;
input  [12:0] data_60_val;
input  [12:0] data_61_val;
input  [12:0] data_62_val;
input  [12:0] data_63_val;
output  [11:0] ap_return_0;
output  [11:0] ap_return_1;
output  [11:0] ap_return_2;
output  [11:0] ap_return_3;
output  [11:0] ap_return_4;
output  [11:0] ap_return_5;
output  [11:0] ap_return_6;
output  [11:0] ap_return_7;
output  [11:0] ap_return_8;
output  [11:0] ap_return_9;
output  [11:0] ap_return_10;
output  [11:0] ap_return_11;
output  [11:0] ap_return_12;
output  [11:0] ap_return_13;
output  [11:0] ap_return_14;
output  [11:0] ap_return_15;
output  [11:0] ap_return_16;
output  [11:0] ap_return_17;
output  [11:0] ap_return_18;
output  [11:0] ap_return_19;
output  [11:0] ap_return_20;
output  [11:0] ap_return_21;
output  [11:0] ap_return_22;
output  [11:0] ap_return_23;
output  [11:0] ap_return_24;
output  [11:0] ap_return_25;
output  [11:0] ap_return_26;
output  [11:0] ap_return_27;
output  [11:0] ap_return_28;
output  [11:0] ap_return_29;
output  [11:0] ap_return_30;
output  [11:0] ap_return_31;
output  [11:0] ap_return_32;
output  [11:0] ap_return_33;
output  [11:0] ap_return_34;
output  [11:0] ap_return_35;
output  [11:0] ap_return_36;
output  [11:0] ap_return_37;
output  [11:0] ap_return_38;
output  [11:0] ap_return_39;
output  [11:0] ap_return_40;
output  [11:0] ap_return_41;
output  [11:0] ap_return_42;
output  [11:0] ap_return_43;
output  [11:0] ap_return_44;
output  [11:0] ap_return_45;
output  [11:0] ap_return_46;
output  [11:0] ap_return_47;
output  [11:0] ap_return_48;
output  [11:0] ap_return_49;
output  [11:0] ap_return_50;
output  [11:0] ap_return_51;
output  [11:0] ap_return_52;
output  [11:0] ap_return_53;
output  [11:0] ap_return_54;
output  [11:0] ap_return_55;
output  [11:0] ap_return_56;
output  [11:0] ap_return_57;
output  [11:0] ap_return_58;
output  [11:0] ap_return_59;
output  [11:0] ap_return_60;
output  [11:0] ap_return_61;
output  [11:0] ap_return_62;
input   ap_rst;

wire   [0:0] icmp_ln45_fu_520_p2;
wire   [11:0] trunc_ln46_fu_526_p1;
wire   [0:0] icmp_ln45_55_fu_538_p2;
wire   [11:0] trunc_ln46_55_fu_544_p1;
wire   [0:0] icmp_ln45_56_fu_556_p2;
wire   [11:0] trunc_ln46_56_fu_562_p1;
wire   [0:0] icmp_ln45_57_fu_574_p2;
wire   [11:0] trunc_ln46_57_fu_580_p1;
wire   [0:0] icmp_ln45_58_fu_592_p2;
wire   [11:0] trunc_ln46_58_fu_598_p1;
wire   [0:0] icmp_ln45_59_fu_610_p2;
wire   [11:0] trunc_ln46_59_fu_616_p1;
wire   [0:0] icmp_ln45_60_fu_628_p2;
wire   [11:0] trunc_ln46_60_fu_634_p1;
wire   [0:0] icmp_ln45_61_fu_646_p2;
wire   [11:0] trunc_ln46_61_fu_652_p1;
wire   [0:0] icmp_ln45_62_fu_664_p2;
wire   [11:0] trunc_ln46_62_fu_670_p1;
wire   [0:0] icmp_ln45_63_fu_682_p2;
wire   [11:0] trunc_ln46_63_fu_688_p1;
wire   [0:0] icmp_ln45_64_fu_700_p2;
wire   [11:0] trunc_ln46_64_fu_706_p1;
wire   [0:0] icmp_ln45_65_fu_718_p2;
wire   [11:0] trunc_ln46_65_fu_724_p1;
wire   [0:0] icmp_ln45_66_fu_736_p2;
wire   [11:0] trunc_ln46_66_fu_742_p1;
wire   [0:0] icmp_ln45_67_fu_754_p2;
wire   [11:0] trunc_ln46_67_fu_760_p1;
wire   [0:0] icmp_ln45_68_fu_772_p2;
wire   [11:0] trunc_ln46_68_fu_778_p1;
wire   [0:0] icmp_ln45_69_fu_790_p2;
wire   [11:0] trunc_ln46_69_fu_796_p1;
wire   [0:0] icmp_ln45_70_fu_808_p2;
wire   [11:0] trunc_ln46_70_fu_814_p1;
wire   [0:0] icmp_ln45_71_fu_826_p2;
wire   [11:0] trunc_ln46_71_fu_832_p1;
wire   [0:0] icmp_ln45_72_fu_844_p2;
wire   [11:0] trunc_ln46_72_fu_850_p1;
wire   [0:0] icmp_ln45_73_fu_862_p2;
wire   [11:0] trunc_ln46_73_fu_868_p1;
wire   [0:0] icmp_ln45_74_fu_880_p2;
wire   [11:0] trunc_ln46_74_fu_886_p1;
wire   [0:0] icmp_ln45_75_fu_898_p2;
wire   [11:0] trunc_ln46_75_fu_904_p1;
wire   [0:0] icmp_ln45_76_fu_916_p2;
wire   [11:0] trunc_ln46_76_fu_922_p1;
wire   [0:0] icmp_ln45_77_fu_934_p2;
wire   [11:0] trunc_ln46_77_fu_940_p1;
wire   [0:0] icmp_ln45_78_fu_952_p2;
wire   [11:0] trunc_ln46_78_fu_958_p1;
wire   [0:0] icmp_ln45_79_fu_970_p2;
wire   [11:0] trunc_ln46_79_fu_976_p1;
wire   [0:0] icmp_ln45_80_fu_988_p2;
wire   [11:0] trunc_ln46_80_fu_994_p1;
wire   [0:0] icmp_ln45_81_fu_1006_p2;
wire   [11:0] trunc_ln46_81_fu_1012_p1;
wire   [0:0] icmp_ln45_82_fu_1024_p2;
wire   [11:0] trunc_ln46_82_fu_1030_p1;
wire   [0:0] icmp_ln45_83_fu_1042_p2;
wire   [11:0] trunc_ln46_83_fu_1048_p1;
wire   [0:0] icmp_ln45_84_fu_1060_p2;
wire   [11:0] trunc_ln46_84_fu_1066_p1;
wire   [0:0] icmp_ln45_85_fu_1078_p2;
wire   [11:0] trunc_ln46_85_fu_1084_p1;
wire   [0:0] icmp_ln45_86_fu_1096_p2;
wire   [11:0] trunc_ln46_86_fu_1102_p1;
wire   [0:0] icmp_ln45_87_fu_1114_p2;
wire   [11:0] trunc_ln46_87_fu_1120_p1;
wire   [0:0] icmp_ln45_88_fu_1132_p2;
wire   [11:0] trunc_ln46_88_fu_1138_p1;
wire   [0:0] icmp_ln45_89_fu_1150_p2;
wire   [11:0] trunc_ln46_89_fu_1156_p1;
wire   [0:0] icmp_ln45_90_fu_1168_p2;
wire   [11:0] trunc_ln46_90_fu_1174_p1;
wire   [0:0] icmp_ln45_91_fu_1186_p2;
wire   [11:0] trunc_ln46_91_fu_1192_p1;
wire   [0:0] icmp_ln45_92_fu_1204_p2;
wire   [11:0] trunc_ln46_92_fu_1210_p1;
wire   [0:0] icmp_ln45_93_fu_1222_p2;
wire   [11:0] trunc_ln46_93_fu_1228_p1;
wire   [0:0] icmp_ln45_94_fu_1240_p2;
wire   [11:0] trunc_ln46_94_fu_1246_p1;
wire   [0:0] icmp_ln45_95_fu_1258_p2;
wire   [11:0] trunc_ln46_95_fu_1264_p1;
wire   [0:0] icmp_ln45_96_fu_1276_p2;
wire   [11:0] trunc_ln46_96_fu_1282_p1;
wire   [0:0] icmp_ln45_97_fu_1294_p2;
wire   [11:0] trunc_ln46_97_fu_1300_p1;
wire   [0:0] icmp_ln45_98_fu_1312_p2;
wire   [11:0] trunc_ln46_98_fu_1318_p1;
wire   [0:0] icmp_ln45_99_fu_1330_p2;
wire   [11:0] trunc_ln46_99_fu_1336_p1;
wire   [0:0] icmp_ln45_100_fu_1348_p2;
wire   [11:0] trunc_ln46_100_fu_1354_p1;
wire   [0:0] icmp_ln45_101_fu_1366_p2;
wire   [11:0] trunc_ln46_101_fu_1372_p1;
wire   [0:0] icmp_ln45_102_fu_1384_p2;
wire   [11:0] trunc_ln46_102_fu_1390_p1;
wire   [0:0] icmp_ln45_103_fu_1402_p2;
wire   [11:0] trunc_ln46_103_fu_1408_p1;
wire   [0:0] icmp_ln45_104_fu_1420_p2;
wire   [11:0] trunc_ln46_104_fu_1426_p1;
wire   [0:0] icmp_ln45_105_fu_1438_p2;
wire   [11:0] trunc_ln46_105_fu_1444_p1;
wire   [0:0] icmp_ln45_106_fu_1456_p2;
wire   [11:0] trunc_ln46_106_fu_1462_p1;
wire   [0:0] icmp_ln45_107_fu_1474_p2;
wire   [11:0] trunc_ln46_107_fu_1480_p1;
wire   [0:0] icmp_ln45_108_fu_1492_p2;
wire   [11:0] trunc_ln46_108_fu_1498_p1;
wire   [0:0] icmp_ln45_109_fu_1510_p2;
wire   [11:0] trunc_ln46_109_fu_1516_p1;
wire   [0:0] icmp_ln45_110_fu_1528_p2;
wire   [11:0] trunc_ln46_110_fu_1534_p1;
wire   [0:0] icmp_ln45_111_fu_1546_p2;
wire   [11:0] trunc_ln46_111_fu_1552_p1;
wire   [0:0] icmp_ln45_112_fu_1564_p2;
wire   [11:0] trunc_ln46_112_fu_1570_p1;
wire   [0:0] icmp_ln45_113_fu_1582_p2;
wire   [11:0] trunc_ln46_113_fu_1588_p1;
wire   [0:0] icmp_ln45_114_fu_1600_p2;
wire   [11:0] trunc_ln46_114_fu_1606_p1;
wire   [0:0] icmp_ln45_115_fu_1618_p2;
wire   [11:0] trunc_ln46_115_fu_1624_p1;
wire   [0:0] icmp_ln45_116_fu_1636_p2;
wire   [11:0] trunc_ln46_116_fu_1642_p1;
wire   [11:0] select_ln45_fu_530_p3;
wire   [11:0] select_ln45_55_fu_548_p3;
wire   [11:0] select_ln45_56_fu_566_p3;
wire   [11:0] select_ln45_57_fu_584_p3;
wire   [11:0] select_ln45_58_fu_602_p3;
wire   [11:0] select_ln45_59_fu_620_p3;
wire   [11:0] select_ln45_60_fu_638_p3;
wire   [11:0] select_ln45_61_fu_656_p3;
wire   [11:0] select_ln45_62_fu_674_p3;
wire   [11:0] select_ln45_63_fu_692_p3;
wire   [11:0] select_ln45_64_fu_710_p3;
wire   [11:0] select_ln45_65_fu_728_p3;
wire   [11:0] select_ln45_66_fu_746_p3;
wire   [11:0] select_ln45_67_fu_764_p3;
wire   [11:0] select_ln45_68_fu_782_p3;
wire   [11:0] select_ln45_69_fu_800_p3;
wire   [11:0] select_ln45_70_fu_818_p3;
wire   [11:0] select_ln45_71_fu_836_p3;
wire   [11:0] select_ln45_72_fu_854_p3;
wire   [11:0] select_ln45_73_fu_872_p3;
wire   [11:0] select_ln45_74_fu_890_p3;
wire   [11:0] select_ln45_75_fu_908_p3;
wire   [11:0] select_ln45_76_fu_926_p3;
wire   [11:0] select_ln45_77_fu_944_p3;
wire   [11:0] select_ln45_78_fu_962_p3;
wire   [11:0] select_ln45_79_fu_980_p3;
wire   [11:0] select_ln45_80_fu_998_p3;
wire   [11:0] select_ln45_81_fu_1016_p3;
wire   [11:0] select_ln45_82_fu_1034_p3;
wire   [11:0] select_ln45_83_fu_1052_p3;
wire   [11:0] select_ln45_84_fu_1070_p3;
wire   [11:0] select_ln45_85_fu_1088_p3;
wire   [11:0] select_ln45_86_fu_1106_p3;
wire   [11:0] select_ln45_87_fu_1124_p3;
wire   [11:0] select_ln45_88_fu_1142_p3;
wire   [11:0] select_ln45_89_fu_1160_p3;
wire   [11:0] select_ln45_90_fu_1178_p3;
wire   [11:0] select_ln45_91_fu_1196_p3;
wire   [11:0] select_ln45_92_fu_1214_p3;
wire   [11:0] select_ln45_93_fu_1232_p3;
wire   [11:0] select_ln45_94_fu_1250_p3;
wire   [11:0] select_ln45_95_fu_1268_p3;
wire   [11:0] select_ln45_96_fu_1286_p3;
wire   [11:0] select_ln45_97_fu_1304_p3;
wire   [11:0] select_ln45_98_fu_1322_p3;
wire   [11:0] select_ln45_99_fu_1340_p3;
wire   [11:0] select_ln45_100_fu_1358_p3;
wire   [11:0] select_ln45_101_fu_1376_p3;
wire   [11:0] select_ln45_102_fu_1394_p3;
wire   [11:0] select_ln45_103_fu_1412_p3;
wire   [11:0] select_ln45_104_fu_1430_p3;
wire   [11:0] select_ln45_105_fu_1448_p3;
wire   [11:0] select_ln45_106_fu_1466_p3;
wire   [11:0] select_ln45_107_fu_1484_p3;
wire   [11:0] select_ln45_108_fu_1502_p3;
wire   [11:0] select_ln45_109_fu_1520_p3;
wire   [11:0] select_ln45_110_fu_1538_p3;
wire   [11:0] select_ln45_111_fu_1556_p3;
wire   [11:0] select_ln45_112_fu_1574_p3;
wire   [11:0] select_ln45_113_fu_1592_p3;
wire   [11:0] select_ln45_114_fu_1610_p3;
wire   [11:0] select_ln45_115_fu_1628_p3;
wire   [11:0] select_ln45_116_fu_1646_p3;

assign ap_ready = 1'b1;

assign select_ln45_100_fu_1358_p3 = ((icmp_ln45_100_fu_1348_p2[0:0] == 1'b1) ? trunc_ln46_100_fu_1354_p1 : 12'd0);

assign select_ln45_101_fu_1376_p3 = ((icmp_ln45_101_fu_1366_p2[0:0] == 1'b1) ? trunc_ln46_101_fu_1372_p1 : 12'd0);

assign select_ln45_102_fu_1394_p3 = ((icmp_ln45_102_fu_1384_p2[0:0] == 1'b1) ? trunc_ln46_102_fu_1390_p1 : 12'd0);

assign select_ln45_103_fu_1412_p3 = ((icmp_ln45_103_fu_1402_p2[0:0] == 1'b1) ? trunc_ln46_103_fu_1408_p1 : 12'd0);

assign select_ln45_104_fu_1430_p3 = ((icmp_ln45_104_fu_1420_p2[0:0] == 1'b1) ? trunc_ln46_104_fu_1426_p1 : 12'd0);

assign select_ln45_105_fu_1448_p3 = ((icmp_ln45_105_fu_1438_p2[0:0] == 1'b1) ? trunc_ln46_105_fu_1444_p1 : 12'd0);

assign select_ln45_106_fu_1466_p3 = ((icmp_ln45_106_fu_1456_p2[0:0] == 1'b1) ? trunc_ln46_106_fu_1462_p1 : 12'd0);

assign select_ln45_107_fu_1484_p3 = ((icmp_ln45_107_fu_1474_p2[0:0] == 1'b1) ? trunc_ln46_107_fu_1480_p1 : 12'd0);

assign select_ln45_108_fu_1502_p3 = ((icmp_ln45_108_fu_1492_p2[0:0] == 1'b1) ? trunc_ln46_108_fu_1498_p1 : 12'd0);

assign select_ln45_109_fu_1520_p3 = ((icmp_ln45_109_fu_1510_p2[0:0] == 1'b1) ? trunc_ln46_109_fu_1516_p1 : 12'd0);

assign select_ln45_110_fu_1538_p3 = ((icmp_ln45_110_fu_1528_p2[0:0] == 1'b1) ? trunc_ln46_110_fu_1534_p1 : 12'd0);

assign select_ln45_111_fu_1556_p3 = ((icmp_ln45_111_fu_1546_p2[0:0] == 1'b1) ? trunc_ln46_111_fu_1552_p1 : 12'd0);

assign select_ln45_112_fu_1574_p3 = ((icmp_ln45_112_fu_1564_p2[0:0] == 1'b1) ? trunc_ln46_112_fu_1570_p1 : 12'd0);

assign select_ln45_113_fu_1592_p3 = ((icmp_ln45_113_fu_1582_p2[0:0] == 1'b1) ? trunc_ln46_113_fu_1588_p1 : 12'd0);

assign select_ln45_114_fu_1610_p3 = ((icmp_ln45_114_fu_1600_p2[0:0] == 1'b1) ? trunc_ln46_114_fu_1606_p1 : 12'd0);

assign select_ln45_115_fu_1628_p3 = ((icmp_ln45_115_fu_1618_p2[0:0] == 1'b1) ? trunc_ln46_115_fu_1624_p1 : 12'd0);

assign select_ln45_116_fu_1646_p3 = ((icmp_ln45_116_fu_1636_p2[0:0] == 1'b1) ? trunc_ln46_116_fu_1642_p1 : 12'd0);

assign select_ln45_55_fu_548_p3 = ((icmp_ln45_55_fu_538_p2[0:0] == 1'b1) ? trunc_ln46_55_fu_544_p1 : 12'd0);

assign select_ln45_56_fu_566_p3 = ((icmp_ln45_56_fu_556_p2[0:0] == 1'b1) ? trunc_ln46_56_fu_562_p1 : 12'd0);

assign select_ln45_57_fu_584_p3 = ((icmp_ln45_57_fu_574_p2[0:0] == 1'b1) ? trunc_ln46_57_fu_580_p1 : 12'd0);

assign select_ln45_58_fu_602_p3 = ((icmp_ln45_58_fu_592_p2[0:0] == 1'b1) ? trunc_ln46_58_fu_598_p1 : 12'd0);

assign select_ln45_59_fu_620_p3 = ((icmp_ln45_59_fu_610_p2[0:0] == 1'b1) ? trunc_ln46_59_fu_616_p1 : 12'd0);

assign select_ln45_60_fu_638_p3 = ((icmp_ln45_60_fu_628_p2[0:0] == 1'b1) ? trunc_ln46_60_fu_634_p1 : 12'd0);

assign select_ln45_61_fu_656_p3 = ((icmp_ln45_61_fu_646_p2[0:0] == 1'b1) ? trunc_ln46_61_fu_652_p1 : 12'd0);

assign select_ln45_62_fu_674_p3 = ((icmp_ln45_62_fu_664_p2[0:0] == 1'b1) ? trunc_ln46_62_fu_670_p1 : 12'd0);

assign select_ln45_63_fu_692_p3 = ((icmp_ln45_63_fu_682_p2[0:0] == 1'b1) ? trunc_ln46_63_fu_688_p1 : 12'd0);

assign select_ln45_64_fu_710_p3 = ((icmp_ln45_64_fu_700_p2[0:0] == 1'b1) ? trunc_ln46_64_fu_706_p1 : 12'd0);

assign select_ln45_65_fu_728_p3 = ((icmp_ln45_65_fu_718_p2[0:0] == 1'b1) ? trunc_ln46_65_fu_724_p1 : 12'd0);

assign select_ln45_66_fu_746_p3 = ((icmp_ln45_66_fu_736_p2[0:0] == 1'b1) ? trunc_ln46_66_fu_742_p1 : 12'd0);

assign select_ln45_67_fu_764_p3 = ((icmp_ln45_67_fu_754_p2[0:0] == 1'b1) ? trunc_ln46_67_fu_760_p1 : 12'd0);

assign select_ln45_68_fu_782_p3 = ((icmp_ln45_68_fu_772_p2[0:0] == 1'b1) ? trunc_ln46_68_fu_778_p1 : 12'd0);

assign select_ln45_69_fu_800_p3 = ((icmp_ln45_69_fu_790_p2[0:0] == 1'b1) ? trunc_ln46_69_fu_796_p1 : 12'd0);

assign select_ln45_70_fu_818_p3 = ((icmp_ln45_70_fu_808_p2[0:0] == 1'b1) ? trunc_ln46_70_fu_814_p1 : 12'd0);

assign select_ln45_71_fu_836_p3 = ((icmp_ln45_71_fu_826_p2[0:0] == 1'b1) ? trunc_ln46_71_fu_832_p1 : 12'd0);

assign select_ln45_72_fu_854_p3 = ((icmp_ln45_72_fu_844_p2[0:0] == 1'b1) ? trunc_ln46_72_fu_850_p1 : 12'd0);

assign select_ln45_73_fu_872_p3 = ((icmp_ln45_73_fu_862_p2[0:0] == 1'b1) ? trunc_ln46_73_fu_868_p1 : 12'd0);

assign select_ln45_74_fu_890_p3 = ((icmp_ln45_74_fu_880_p2[0:0] == 1'b1) ? trunc_ln46_74_fu_886_p1 : 12'd0);

assign select_ln45_75_fu_908_p3 = ((icmp_ln45_75_fu_898_p2[0:0] == 1'b1) ? trunc_ln46_75_fu_904_p1 : 12'd0);

assign select_ln45_76_fu_926_p3 = ((icmp_ln45_76_fu_916_p2[0:0] == 1'b1) ? trunc_ln46_76_fu_922_p1 : 12'd0);

assign select_ln45_77_fu_944_p3 = ((icmp_ln45_77_fu_934_p2[0:0] == 1'b1) ? trunc_ln46_77_fu_940_p1 : 12'd0);

assign select_ln45_78_fu_962_p3 = ((icmp_ln45_78_fu_952_p2[0:0] == 1'b1) ? trunc_ln46_78_fu_958_p1 : 12'd0);

assign select_ln45_79_fu_980_p3 = ((icmp_ln45_79_fu_970_p2[0:0] == 1'b1) ? trunc_ln46_79_fu_976_p1 : 12'd0);

assign select_ln45_80_fu_998_p3 = ((icmp_ln45_80_fu_988_p2[0:0] == 1'b1) ? trunc_ln46_80_fu_994_p1 : 12'd0);

assign select_ln45_81_fu_1016_p3 = ((icmp_ln45_81_fu_1006_p2[0:0] == 1'b1) ? trunc_ln46_81_fu_1012_p1 : 12'd0);

assign select_ln45_82_fu_1034_p3 = ((icmp_ln45_82_fu_1024_p2[0:0] == 1'b1) ? trunc_ln46_82_fu_1030_p1 : 12'd0);

assign select_ln45_83_fu_1052_p3 = ((icmp_ln45_83_fu_1042_p2[0:0] == 1'b1) ? trunc_ln46_83_fu_1048_p1 : 12'd0);

assign select_ln45_84_fu_1070_p3 = ((icmp_ln45_84_fu_1060_p2[0:0] == 1'b1) ? trunc_ln46_84_fu_1066_p1 : 12'd0);

assign select_ln45_85_fu_1088_p3 = ((icmp_ln45_85_fu_1078_p2[0:0] == 1'b1) ? trunc_ln46_85_fu_1084_p1 : 12'd0);

assign select_ln45_86_fu_1106_p3 = ((icmp_ln45_86_fu_1096_p2[0:0] == 1'b1) ? trunc_ln46_86_fu_1102_p1 : 12'd0);

assign select_ln45_87_fu_1124_p3 = ((icmp_ln45_87_fu_1114_p2[0:0] == 1'b1) ? trunc_ln46_87_fu_1120_p1 : 12'd0);

assign select_ln45_88_fu_1142_p3 = ((icmp_ln45_88_fu_1132_p2[0:0] == 1'b1) ? trunc_ln46_88_fu_1138_p1 : 12'd0);

assign select_ln45_89_fu_1160_p3 = ((icmp_ln45_89_fu_1150_p2[0:0] == 1'b1) ? trunc_ln46_89_fu_1156_p1 : 12'd0);

assign select_ln45_90_fu_1178_p3 = ((icmp_ln45_90_fu_1168_p2[0:0] == 1'b1) ? trunc_ln46_90_fu_1174_p1 : 12'd0);

assign select_ln45_91_fu_1196_p3 = ((icmp_ln45_91_fu_1186_p2[0:0] == 1'b1) ? trunc_ln46_91_fu_1192_p1 : 12'd0);

assign select_ln45_92_fu_1214_p3 = ((icmp_ln45_92_fu_1204_p2[0:0] == 1'b1) ? trunc_ln46_92_fu_1210_p1 : 12'd0);

assign select_ln45_93_fu_1232_p3 = ((icmp_ln45_93_fu_1222_p2[0:0] == 1'b1) ? trunc_ln46_93_fu_1228_p1 : 12'd0);

assign select_ln45_94_fu_1250_p3 = ((icmp_ln45_94_fu_1240_p2[0:0] == 1'b1) ? trunc_ln46_94_fu_1246_p1 : 12'd0);

assign select_ln45_95_fu_1268_p3 = ((icmp_ln45_95_fu_1258_p2[0:0] == 1'b1) ? trunc_ln46_95_fu_1264_p1 : 12'd0);

assign select_ln45_96_fu_1286_p3 = ((icmp_ln45_96_fu_1276_p2[0:0] == 1'b1) ? trunc_ln46_96_fu_1282_p1 : 12'd0);

assign select_ln45_97_fu_1304_p3 = ((icmp_ln45_97_fu_1294_p2[0:0] == 1'b1) ? trunc_ln46_97_fu_1300_p1 : 12'd0);

assign select_ln45_98_fu_1322_p3 = ((icmp_ln45_98_fu_1312_p2[0:0] == 1'b1) ? trunc_ln46_98_fu_1318_p1 : 12'd0);

assign select_ln45_99_fu_1340_p3 = ((icmp_ln45_99_fu_1330_p2[0:0] == 1'b1) ? trunc_ln46_99_fu_1336_p1 : 12'd0);

assign select_ln45_fu_530_p3 = ((icmp_ln45_fu_520_p2[0:0] == 1'b1) ? trunc_ln46_fu_526_p1 : 12'd0);

assign trunc_ln46_100_fu_1354_p1 = data_47_val[11:0];

assign trunc_ln46_101_fu_1372_p1 = data_48_val[11:0];

assign trunc_ln46_102_fu_1390_p1 = data_49_val[11:0];

assign trunc_ln46_103_fu_1408_p1 = data_50_val[11:0];

assign trunc_ln46_104_fu_1426_p1 = data_51_val[11:0];

assign trunc_ln46_105_fu_1444_p1 = data_52_val[11:0];

assign trunc_ln46_106_fu_1462_p1 = data_53_val[11:0];

assign trunc_ln46_107_fu_1480_p1 = data_54_val[11:0];

assign trunc_ln46_108_fu_1498_p1 = data_55_val[11:0];

assign trunc_ln46_109_fu_1516_p1 = data_56_val[11:0];

assign trunc_ln46_110_fu_1534_p1 = data_57_val[11:0];

assign trunc_ln46_111_fu_1552_p1 = data_58_val[11:0];

assign trunc_ln46_112_fu_1570_p1 = data_59_val[11:0];

assign trunc_ln46_113_fu_1588_p1 = data_60_val[11:0];

assign trunc_ln46_114_fu_1606_p1 = data_61_val[11:0];

assign trunc_ln46_115_fu_1624_p1 = data_62_val[11:0];

assign trunc_ln46_116_fu_1642_p1 = data_63_val[11:0];

assign trunc_ln46_55_fu_544_p1 = data_1_val[11:0];

assign trunc_ln46_56_fu_562_p1 = data_2_val[11:0];

assign trunc_ln46_57_fu_580_p1 = data_3_val[11:0];

assign trunc_ln46_58_fu_598_p1 = data_4_val[11:0];

assign trunc_ln46_59_fu_616_p1 = data_5_val[11:0];

assign trunc_ln46_60_fu_634_p1 = data_6_val[11:0];

assign trunc_ln46_61_fu_652_p1 = data_7_val[11:0];

assign trunc_ln46_62_fu_670_p1 = data_8_val[11:0];

assign trunc_ln46_63_fu_688_p1 = data_9_val[11:0];

assign trunc_ln46_64_fu_706_p1 = data_10_val[11:0];

assign trunc_ln46_65_fu_724_p1 = data_11_val[11:0];

assign trunc_ln46_66_fu_742_p1 = data_12_val[11:0];

assign trunc_ln46_67_fu_760_p1 = data_13_val[11:0];

assign trunc_ln46_68_fu_778_p1 = data_14_val[11:0];

assign trunc_ln46_69_fu_796_p1 = data_15_val[11:0];

assign trunc_ln46_70_fu_814_p1 = data_16_val[11:0];

assign trunc_ln46_71_fu_832_p1 = data_17_val[11:0];

assign trunc_ln46_72_fu_850_p1 = data_18_val[11:0];

assign trunc_ln46_73_fu_868_p1 = data_19_val[11:0];

assign trunc_ln46_74_fu_886_p1 = data_20_val[11:0];

assign trunc_ln46_75_fu_904_p1 = data_21_val[11:0];

assign trunc_ln46_76_fu_922_p1 = data_22_val[11:0];

assign trunc_ln46_77_fu_940_p1 = data_23_val[11:0];

assign trunc_ln46_78_fu_958_p1 = data_24_val[11:0];

assign trunc_ln46_79_fu_976_p1 = data_25_val[11:0];

assign trunc_ln46_80_fu_994_p1 = data_26_val[11:0];

assign trunc_ln46_81_fu_1012_p1 = data_27_val[11:0];

assign trunc_ln46_82_fu_1030_p1 = data_28_val[11:0];

assign trunc_ln46_83_fu_1048_p1 = data_29_val[11:0];

assign trunc_ln46_84_fu_1066_p1 = data_30_val[11:0];

assign trunc_ln46_85_fu_1084_p1 = data_31_val[11:0];

assign trunc_ln46_86_fu_1102_p1 = data_33_val[11:0];

assign trunc_ln46_87_fu_1120_p1 = data_34_val[11:0];

assign trunc_ln46_88_fu_1138_p1 = data_35_val[11:0];

assign trunc_ln46_89_fu_1156_p1 = data_36_val[11:0];

assign trunc_ln46_90_fu_1174_p1 = data_37_val[11:0];

assign trunc_ln46_91_fu_1192_p1 = data_38_val[11:0];

assign trunc_ln46_92_fu_1210_p1 = data_39_val[11:0];

assign trunc_ln46_93_fu_1228_p1 = data_40_val[11:0];

assign trunc_ln46_94_fu_1246_p1 = data_41_val[11:0];

assign trunc_ln46_95_fu_1264_p1 = data_42_val[11:0];

assign trunc_ln46_96_fu_1282_p1 = data_43_val[11:0];

assign trunc_ln46_97_fu_1300_p1 = data_44_val[11:0];

assign trunc_ln46_98_fu_1318_p1 = data_45_val[11:0];

assign trunc_ln46_99_fu_1336_p1 = data_46_val[11:0];

assign trunc_ln46_fu_526_p1 = data_0_val[11:0];

assign ap_return_0 = select_ln45_fu_530_p3;

assign ap_return_1 = select_ln45_55_fu_548_p3;

assign ap_return_10 = select_ln45_64_fu_710_p3;

assign ap_return_11 = select_ln45_65_fu_728_p3;

assign ap_return_12 = select_ln45_66_fu_746_p3;

assign ap_return_13 = select_ln45_67_fu_764_p3;

assign ap_return_14 = select_ln45_68_fu_782_p3;

assign ap_return_15 = select_ln45_69_fu_800_p3;

assign ap_return_16 = select_ln45_70_fu_818_p3;

assign ap_return_17 = select_ln45_71_fu_836_p3;

assign ap_return_18 = select_ln45_72_fu_854_p3;

assign ap_return_19 = select_ln45_73_fu_872_p3;

assign ap_return_2 = select_ln45_56_fu_566_p3;

assign ap_return_20 = select_ln45_74_fu_890_p3;

assign ap_return_21 = select_ln45_75_fu_908_p3;

assign ap_return_22 = select_ln45_76_fu_926_p3;

assign ap_return_23 = select_ln45_77_fu_944_p3;

assign ap_return_24 = select_ln45_78_fu_962_p3;

assign ap_return_25 = select_ln45_79_fu_980_p3;

assign ap_return_26 = select_ln45_80_fu_998_p3;

assign ap_return_27 = select_ln45_81_fu_1016_p3;

assign ap_return_28 = select_ln45_82_fu_1034_p3;

assign ap_return_29 = select_ln45_83_fu_1052_p3;

assign ap_return_3 = select_ln45_57_fu_584_p3;

assign ap_return_30 = select_ln45_84_fu_1070_p3;

assign ap_return_31 = select_ln45_85_fu_1088_p3;

assign ap_return_32 = select_ln45_86_fu_1106_p3;

assign ap_return_33 = select_ln45_87_fu_1124_p3;

assign ap_return_34 = select_ln45_88_fu_1142_p3;

assign ap_return_35 = select_ln45_89_fu_1160_p3;

assign ap_return_36 = select_ln45_90_fu_1178_p3;

assign ap_return_37 = select_ln45_91_fu_1196_p3;

assign ap_return_38 = select_ln45_92_fu_1214_p3;

assign ap_return_39 = select_ln45_93_fu_1232_p3;

assign ap_return_4 = select_ln45_58_fu_602_p3;

assign ap_return_40 = select_ln45_94_fu_1250_p3;

assign ap_return_41 = select_ln45_95_fu_1268_p3;

assign ap_return_42 = select_ln45_96_fu_1286_p3;

assign ap_return_43 = select_ln45_97_fu_1304_p3;

assign ap_return_44 = select_ln45_98_fu_1322_p3;

assign ap_return_45 = select_ln45_99_fu_1340_p3;

assign ap_return_46 = select_ln45_100_fu_1358_p3;

assign ap_return_47 = select_ln45_101_fu_1376_p3;

assign ap_return_48 = select_ln45_102_fu_1394_p3;

assign ap_return_49 = select_ln45_103_fu_1412_p3;

assign ap_return_5 = select_ln45_59_fu_620_p3;

assign ap_return_50 = select_ln45_104_fu_1430_p3;

assign ap_return_51 = select_ln45_105_fu_1448_p3;

assign ap_return_52 = select_ln45_106_fu_1466_p3;

assign ap_return_53 = select_ln45_107_fu_1484_p3;

assign ap_return_54 = select_ln45_108_fu_1502_p3;

assign ap_return_55 = select_ln45_109_fu_1520_p3;

assign ap_return_56 = select_ln45_110_fu_1538_p3;

assign ap_return_57 = select_ln45_111_fu_1556_p3;

assign ap_return_58 = select_ln45_112_fu_1574_p3;

assign ap_return_59 = select_ln45_113_fu_1592_p3;

assign ap_return_6 = select_ln45_60_fu_638_p3;

assign ap_return_60 = select_ln45_114_fu_1610_p3;

assign ap_return_61 = select_ln45_115_fu_1628_p3;

assign ap_return_62 = select_ln45_116_fu_1646_p3;

assign ap_return_7 = select_ln45_61_fu_656_p3;

assign ap_return_8 = select_ln45_62_fu_674_p3;

assign ap_return_9 = select_ln45_63_fu_692_p3;

assign icmp_ln45_100_fu_1348_p2 = (($signed(data_47_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_101_fu_1366_p2 = (($signed(data_48_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_102_fu_1384_p2 = (($signed(data_49_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_103_fu_1402_p2 = (($signed(data_50_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_104_fu_1420_p2 = (($signed(data_51_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_105_fu_1438_p2 = (($signed(data_52_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_106_fu_1456_p2 = (($signed(data_53_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_107_fu_1474_p2 = (($signed(data_54_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_108_fu_1492_p2 = (($signed(data_55_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_109_fu_1510_p2 = (($signed(data_56_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_110_fu_1528_p2 = (($signed(data_57_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_111_fu_1546_p2 = (($signed(data_58_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_112_fu_1564_p2 = (($signed(data_59_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_113_fu_1582_p2 = (($signed(data_60_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_114_fu_1600_p2 = (($signed(data_61_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_115_fu_1618_p2 = (($signed(data_62_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_116_fu_1636_p2 = (($signed(data_63_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_55_fu_538_p2 = (($signed(data_1_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_56_fu_556_p2 = (($signed(data_2_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_57_fu_574_p2 = (($signed(data_3_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_58_fu_592_p2 = (($signed(data_4_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_59_fu_610_p2 = (($signed(data_5_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_60_fu_628_p2 = (($signed(data_6_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_61_fu_646_p2 = (($signed(data_7_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_62_fu_664_p2 = (($signed(data_8_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_63_fu_682_p2 = (($signed(data_9_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_64_fu_700_p2 = (($signed(data_10_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_65_fu_718_p2 = (($signed(data_11_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_66_fu_736_p2 = (($signed(data_12_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_67_fu_754_p2 = (($signed(data_13_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_68_fu_772_p2 = (($signed(data_14_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_69_fu_790_p2 = (($signed(data_15_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_70_fu_808_p2 = (($signed(data_16_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_71_fu_826_p2 = (($signed(data_17_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_72_fu_844_p2 = (($signed(data_18_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_73_fu_862_p2 = (($signed(data_19_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_74_fu_880_p2 = (($signed(data_20_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_75_fu_898_p2 = (($signed(data_21_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_76_fu_916_p2 = (($signed(data_22_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_77_fu_934_p2 = (($signed(data_23_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_78_fu_952_p2 = (($signed(data_24_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_79_fu_970_p2 = (($signed(data_25_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_80_fu_988_p2 = (($signed(data_26_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_81_fu_1006_p2 = (($signed(data_27_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_82_fu_1024_p2 = (($signed(data_28_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_83_fu_1042_p2 = (($signed(data_29_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_84_fu_1060_p2 = (($signed(data_30_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_85_fu_1078_p2 = (($signed(data_31_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_86_fu_1096_p2 = (($signed(data_33_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_87_fu_1114_p2 = (($signed(data_34_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_88_fu_1132_p2 = (($signed(data_35_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_89_fu_1150_p2 = (($signed(data_36_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_90_fu_1168_p2 = (($signed(data_37_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_91_fu_1186_p2 = (($signed(data_38_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_92_fu_1204_p2 = (($signed(data_39_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_93_fu_1222_p2 = (($signed(data_40_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_94_fu_1240_p2 = (($signed(data_41_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_95_fu_1258_p2 = (($signed(data_42_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_96_fu_1276_p2 = (($signed(data_43_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_97_fu_1294_p2 = (($signed(data_44_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_98_fu_1312_p2 = (($signed(data_45_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_99_fu_1330_p2 = (($signed(data_46_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_520_p2 = (($signed(data_0_val) > $signed(13'd0)) ? 1'b1 : 1'b0);

endmodule //myproject_relu_ap_fixed_13_6_5_3_0_ap_ufixed_12_5_5_3_0_ReLU_config6_s
